//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Config {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Config() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.Config", typeof(Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ConfigDialog_Title {
            get {
                return ResourceManager.GetString("ConfigDialog_Title", resourceCulture);
            }
        }
        
        public static string Config_RpcLevel_Disabled {
            get {
                return ResourceManager.GetString("Config_RpcLevel_Disabled", resourceCulture);
            }
        }
        
        public static string Config_RpcLevel_Enabled {
            get {
                return ResourceManager.GetString("Config_RpcLevel_Enabled", resourceCulture);
            }
        }
        
        public static string Config_RpcLevel_TimeOnly {
            get {
                return ResourceManager.GetString("Config_RpcLevel_TimeOnly", resourceCulture);
            }
        }
        
        public static string Config_PropFields_All {
            get {
                return ResourceManager.GetString("Config_PropFields_All", resourceCulture);
            }
        }
        
        public static string Config_PropFields_None {
            get {
                return ResourceManager.GetString("Config_PropFields_None", resourceCulture);
            }
        }
        
        public static string Config_PropFields_NonText {
            get {
                return ResourceManager.GetString("Config_PropFields_NonText", resourceCulture);
            }
        }
        
        public static string Config_Theme_Default {
            get {
                return ResourceManager.GetString("Config_Theme_Default", resourceCulture);
            }
        }
        
        public static string Config_Theme_Light {
            get {
                return ResourceManager.GetString("Config_Theme_Light", resourceCulture);
            }
        }
        
        public static string Config_Theme_Dark {
            get {
                return ResourceManager.GetString("Config_Theme_Dark", resourceCulture);
            }
        }
        
        public static string Config_SaveFrames_WithVideo {
            get {
                return ResourceManager.GetString("Config_SaveFrames_WithVideo", resourceCulture);
            }
        }
        
        public static string Config_SaveFrames_WithSubtitles {
            get {
                return ResourceManager.GetString("Config_SaveFrames_WithSubtitles", resourceCulture);
            }
        }
        
        public static string Config_Label_CpsWarnThreshold {
            get {
                return ResourceManager.GetString("Config_Label_CpsWarnThreshold", resourceCulture);
            }
        }
        
        public static string Config_Label_CpsWhitespace {
            get {
                return ResourceManager.GetString("Config_Label_CpsWhitespace", resourceCulture);
            }
        }
        
        public static string Config_Label_CpsPunctuation {
            get {
                return ResourceManager.GetString("Config_Label_CpsPunctuation", resourceCulture);
            }
        }
        
        public static string Config_Label_SoftLinebreaks {
            get {
                return ResourceManager.GetString("Config_Label_SoftLinebreaks", resourceCulture);
            }
        }
        
        public static string Config_Label_SoftLinebreaks_ToolTip {
            get {
                return ResourceManager.GetString("Config_Label_SoftLinebreaks_ToolTip", resourceCulture);
            }
        }
        
        public static string Config_Label_DefaultLayer {
            get {
                return ResourceManager.GetString("Config_Label_DefaultLayer", resourceCulture);
            }
        }
        
        public static string Config_Label_DisplayLanguage {
            get {
                return ResourceManager.GetString("Config_Label_DisplayLanguage", resourceCulture);
            }
        }
        
        public static string Config_Label_SpellcheckLanguage {
            get {
                return ResourceManager.GetString("Config_Label_SpellcheckLanguage", resourceCulture);
            }
        }
        
        public static string Config_Label_RichPresence {
            get {
                return ResourceManager.GetString("Config_Label_RichPresence", resourceCulture);
            }
        }
        
        public static string Config_Label_PropagateChanges {
            get {
                return ResourceManager.GetString("Config_Label_PropagateChanges", resourceCulture);
            }
        }
        
        public static string Config_Label_PropagateChanges_ToolTip {
            get {
                return ResourceManager.GetString("Config_Label_PropagateChanges_ToolTip", resourceCulture);
            }
        }
        
        public static string Config_Label_AutosaveEnabled {
            get {
                return ResourceManager.GetString("Config_Label_AutosaveEnabled", resourceCulture);
            }
        }
        
        public static string Config_Label_SaveFrames {
            get {
                return ResourceManager.GetString("Config_Label_SaveFrames", resourceCulture);
            }
        }
        
        public static string Config_Label_AutosaveInterval {
            get {
                return ResourceManager.GetString("Config_Label_AutosaveInterval", resourceCulture);
            }
        }
        
        public static string Config_Label_Theme {
            get {
                return ResourceManager.GetString("Config_Label_Theme", resourceCulture);
            }
        }
        
        public static string Config_Label_EditorFs {
            get {
                return ResourceManager.GetString("Config_Label_EditorFs", resourceCulture);
            }
        }
        
        public static string Config_Label_GridFs {
            get {
                return ResourceManager.GetString("Config_Label_GridFs", resourceCulture);
            }
        }
        
        public static string Config_Label_ReferenceFs {
            get {
                return ResourceManager.GetString("Config_Label_ReferenceFs", resourceCulture);
            }
        }
        
        public static string Config_Label_GridPadding {
            get {
                return ResourceManager.GetString("Config_Label_GridPadding", resourceCulture);
            }
        }
        
        public static string Config_Header_Ssa {
            get {
                return ResourceManager.GetString("Config_Header_Ssa", resourceCulture);
            }
        }
        
        public static string Config_Header_Behavior {
            get {
                return ResourceManager.GetString("Config_Header_Behavior", resourceCulture);
            }
        }
        
        public static string Config_Header_Appearance {
            get {
                return ResourceManager.GetString("Config_Header_Appearance", resourceCulture);
            }
        }
        
        public static string Config_Label_LineWidthPunctuation {
            get {
                return ResourceManager.GetString("Config_Label_LineWidthPunctuation", resourceCulture);
            }
        }
        
        public static string Config_Label_LineWidthWhitespace {
            get {
                return ResourceManager.GetString("Config_Label_LineWidthWhitespace", resourceCulture);
            }
        }
        
        public static string Config_Label_RestartRequired {
            get {
                return ResourceManager.GetString("Config_Label_RestartRequired", resourceCulture);
            }
        }
        
        public static string ProjectConfigDialog_Title {
            get {
                return ResourceManager.GetString("ProjectConfigDialog_Title", resourceCulture);
            }
        }
        
        public static string Config_Header_Spellchecking {
            get {
                return ResourceManager.GetString("Config_Header_Spellchecking", resourceCulture);
            }
        }
        
        public static string Config_Button_Add {
            get {
                return ResourceManager.GetString("Config_Button_Add", resourceCulture);
            }
        }
        
        public static string Config_Button_Remove {
            get {
                return ResourceManager.GetString("Config_Button_Remove", resourceCulture);
            }
        }
        
        public static string Config_CustomWordBox_Watermark {
            get {
                return ResourceManager.GetString("Config_CustomWordBox_Watermark", resourceCulture);
            }
        }
        
        public static string Config_Label_AutoloadAudioTracks {
            get {
                return ResourceManager.GetString("Config_Label_AutoloadAudioTracks", resourceCulture);
            }
        }
        
        public static string Config_Label_AutoloadAudioTracks_ToolTip {
            get {
                return ResourceManager.GetString("Config_Label_AutoloadAudioTracks_ToolTip", resourceCulture);
            }
        }
    }
}
