//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Config {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Config() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.Config", typeof(Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ConfigDialog_Title {
            get {
                return ResourceManager.GetString("ConfigDialog_Title", resourceCulture);
            }
        }
        
        public static string Config_RpcLevel_Disabled {
            get {
                return ResourceManager.GetString("Config_RpcLevel_Disabled", resourceCulture);
            }
        }
        
        public static string Config_RpcLevel_Enabled {
            get {
                return ResourceManager.GetString("Config_RpcLevel_Enabled", resourceCulture);
            }
        }
        
        public static string Config_RpcLevel_TimeOnly {
            get {
                return ResourceManager.GetString("Config_RpcLevel_TimeOnly", resourceCulture);
            }
        }
        
        public static string Config_PropFields_All {
            get {
                return ResourceManager.GetString("Config_PropFields_All", resourceCulture);
            }
        }
        
        public static string Config_PropFields_None {
            get {
                return ResourceManager.GetString("Config_PropFields_None", resourceCulture);
            }
        }
        
        public static string Config_PropFields_NonText {
            get {
                return ResourceManager.GetString("Config_PropFields_NonText", resourceCulture);
            }
        }
        
        public static string Config_Theme_Default {
            get {
                return ResourceManager.GetString("Config_Theme_Default", resourceCulture);
            }
        }
        
        public static string Config_Theme_Light {
            get {
                return ResourceManager.GetString("Config_Theme_Light", resourceCulture);
            }
        }
        
        public static string Config_Theme_Dark {
            get {
                return ResourceManager.GetString("Config_Theme_Dark", resourceCulture);
            }
        }
        
        public static string Config_SaveFrames_WithVideo {
            get {
                return ResourceManager.GetString("Config_SaveFrames_WithVideo", resourceCulture);
            }
        }
        
        public static string Config_SaveFrames_WithSubtitles {
            get {
                return ResourceManager.GetString("Config_SaveFrames_WithSubtitles", resourceCulture);
            }
        }
    }
}
