//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileModified {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileModified() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.FileModified", typeof(FileModified).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string FileModified_WindowTitle {
            get {
                return ResourceManager.GetString("FileModified_WindowTitle", resourceCulture);
            }
        }
        
        public static string FileModified_CallToAction {
            get {
                return ResourceManager.GetString("FileModified_CallToAction", resourceCulture);
            }
        }
        
        public static string FileModified_Recommendation {
            get {
                return ResourceManager.GetString("FileModified_Recommendation", resourceCulture);
            }
        }
        
        public static string FileModified_Header {
            get {
                return ResourceManager.GetString("FileModified_Header", resourceCulture);
            }
        }
        
        public static string FileModified_Button_Ignore {
            get {
                return ResourceManager.GetString("FileModified_Button_Ignore", resourceCulture);
            }
        }
        
        public static string FileModified_Button_SaveAs {
            get {
                return ResourceManager.GetString("FileModified_Button_SaveAs", resourceCulture);
            }
        }
    }
}
