//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Git {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Git() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ameko.I18N.Git", typeof(Git).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        public static string Git_Button_Commit {
            get {
                return ResourceManager.GetString("Git_Button_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit changes on {0}.
        /// </summary>
        public static string Git_Button_Commit_ToolTip {
            get {
                return ResourceManager.GetString("Git_Button_Commit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull.
        /// </summary>
        public static string Git_Button_Pull_ToolTip {
            get {
                return ResourceManager.GetString("Git_Button_Pull_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string Git_Button_Push_ToolTip {
            get {
                return ResourceManager.GetString("Git_Button_Push_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Git_Button_Refresh_ToolTip {
            get {
                return ResourceManager.GetString("Git_Button_Refresh_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage changes.
        /// </summary>
        public static string Git_Button_Stage_ToolTip {
            get {
                return ResourceManager.GetString("Git_Button_Stage_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stash.
        /// </summary>
        public static string Git_Button_Stash {
            get {
                return ResourceManager.GetString("Git_Button_Stash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stash changes.
        /// </summary>
        public static string Git_Button_Stash_ToolTip {
            get {
                return ResourceManager.GetString("Git_Button_Stash_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstage changes.
        /// </summary>
        public static string Git_Button_Unstage_ToolTip {
            get {
                return ResourceManager.GetString("Git_Button_Unstage_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit Message.
        /// </summary>
        public static string Git_CommitBox_Watermark {
            get {
                return ResourceManager.GetString("Git_CommitBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest commits on {0}:.
        /// </summary>
        public static string Git_LatestCommits {
            get {
                return ResourceManager.GetString("Git_LatestCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s nothing to commit at this time..
        /// </summary>
        public static string Git_NothingToCommit {
            get {
                return ResourceManager.GetString("Git_NothingToCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Git repository detected..
        /// </summary>
        public static string Git_NotInRepo {
            get {
                return ResourceManager.GetString("Git_NotInRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use Git features, open a Solution in a folder containing a repository..
        /// </summary>
        public static string Git_NotInRepo_Tutorial {
            get {
                return ResourceManager.GetString("Git_NotInRepo_Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A .git directory was detected, but libgit2 is unable to process it. Make sure this repository is marked as &quot;safe&quot; in your .gitconfig..
        /// </summary>
        public static string Git_PotentialOwnershipIssue {
            get {
                return ResourceManager.GetString("Git_PotentialOwnershipIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staged Changes.
        /// </summary>
        public static string Git_StagedChanges {
            get {
                return ResourceManager.GetString("Git_StagedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstaged Changes.
        /// </summary>
        public static string Git_UnstagedChanges {
            get {
                return ResourceManager.GetString("Git_UnstagedChanges", resourceCulture);
            }
        }
    }
}
