//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Git {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Git() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.Git", typeof(Git).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Git_NotInRepo {
            get {
                return ResourceManager.GetString("Git_NotInRepo", resourceCulture);
            }
        }
        
        public static string Git_NotInRepo_Tutorial {
            get {
                return ResourceManager.GetString("Git_NotInRepo_Tutorial", resourceCulture);
            }
        }
        
        public static string Git_StagedChanges {
            get {
                return ResourceManager.GetString("Git_StagedChanges", resourceCulture);
            }
        }
        
        public static string Git_UnstagedChanges {
            get {
                return ResourceManager.GetString("Git_UnstagedChanges", resourceCulture);
            }
        }
        
        public static string Git_Button_Unstage_ToolTip {
            get {
                return ResourceManager.GetString("Git_Button_Unstage_ToolTip", resourceCulture);
            }
        }
        
        public static string Git_Button_Stage_ToolTip {
            get {
                return ResourceManager.GetString("Git_Button_Stage_ToolTip", resourceCulture);
            }
        }
        
        public static string Git_Button_Commit {
            get {
                return ResourceManager.GetString("Git_Button_Commit", resourceCulture);
            }
        }
        
        public static string Git_Button_Stash {
            get {
                return ResourceManager.GetString("Git_Button_Stash", resourceCulture);
            }
        }
        
        public static string Git_Button_Commit_ToolTip {
            get {
                return ResourceManager.GetString("Git_Button_Commit_ToolTip", resourceCulture);
            }
        }
        
        public static string Git_Button_Stash_ToolTip {
            get {
                return ResourceManager.GetString("Git_Button_Stash_ToolTip", resourceCulture);
            }
        }
        
        public static string Git_Button_Refresh_ToolTip {
            get {
                return ResourceManager.GetString("Git_Button_Refresh_ToolTip", resourceCulture);
            }
        }
        
        public static string Git_CommitBox_Watermark {
            get {
                return ResourceManager.GetString("Git_CommitBox_Watermark", resourceCulture);
            }
        }
        
        public static string Git_PotentialOwnershipIssue {
            get {
                return ResourceManager.GetString("Git_PotentialOwnershipIssue", resourceCulture);
            }
        }
        
        public static string Git_NothingToCommit {
            get {
                return ResourceManager.GetString("Git_NothingToCommit", resourceCulture);
            }
        }
        
        public static string Git_Button_Pull_ToolTip {
            get {
                return ResourceManager.GetString("Git_Button_Pull_ToolTip", resourceCulture);
            }
        }
        
        public static string Git_LatestCommits {
            get {
                return ResourceManager.GetString("Git_LatestCommits", resourceCulture);
            }
        }
        
        public static string Git_Button_Push_ToolTip {
            get {
                return ResourceManager.GetString("Git_Button_Push_ToolTip", resourceCulture);
            }
        }
    }
}
