//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Keybinds {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Keybinds() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.Keybinds", typeof(Keybinds).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string KeybindsWindow_Title {
            get {
                return ResourceManager.GetString("KeybindsWindow_Title", resourceCulture);
            }
        }
        
        public static string Keybinds_Header_Identifier {
            get {
                return ResourceManager.GetString("Keybinds_Header_Identifier", resourceCulture);
            }
        }
        
        public static string Keybinds_Header_Keybind {
            get {
                return ResourceManager.GetString("Keybinds_Header_Keybind", resourceCulture);
            }
        }
        
        public static string Keybinds_Header_Context {
            get {
                return ResourceManager.GetString("Keybinds_Header_Context", resourceCulture);
            }
        }
        
        public static string KeybindContext_None {
            get {
                return ResourceManager.GetString("KeybindContext_None", resourceCulture);
            }
        }
        
        public static string KeybindContext_Global {
            get {
                return ResourceManager.GetString("KeybindContext_Global", resourceCulture);
            }
        }
        
        public static string KeybindContext_Video {
            get {
                return ResourceManager.GetString("KeybindContext_Video", resourceCulture);
            }
        }
        
        public static string KeybindContext_Audio {
            get {
                return ResourceManager.GetString("KeybindContext_Audio", resourceCulture);
            }
        }
        
        public static string KeybindContext_Grid {
            get {
                return ResourceManager.GetString("KeybindContext_Grid", resourceCulture);
            }
        }
        
        public static string Keybinds_Button_Save {
            get {
                return ResourceManager.GetString("Keybinds_Button_Save", resourceCulture);
            }
        }
        
        public static string KeybindContext_Editor {
            get {
                return ResourceManager.GetString("KeybindContext_Editor", resourceCulture);
            }
        }
        
        public static string Keybinds_Button_Remove_ToolTip {
            get {
                return ResourceManager.GetString("Keybinds_Button_Remove_ToolTip", resourceCulture);
            }
        }
        
        public static string Keybinds_Button_Reset {
            get {
                return ResourceManager.GetString("Keybinds_Button_Reset", resourceCulture);
            }
        }
    }
}
