//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Other {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Other() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.Other", typeof(Other).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string LogWindow_Title {
            get {
                return ResourceManager.GetString("LogWindow_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_RemoveDocument_Title {
            get {
                return ResourceManager.GetString("MsgBox_RemoveDocument_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_RemoveDocument_Body {
            get {
                return ResourceManager.GetString("MsgBox_RemoveDocument_Body", resourceCulture);
            }
        }
        
        public static string MsgBox_RemoveDirectory_Title {
            get {
                return ResourceManager.GetString("MsgBox_RemoveDirectory_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_RemoveDirectory_Body {
            get {
                return ResourceManager.GetString("MsgBox_RemoveDirectory_Body", resourceCulture);
            }
        }
        
        public static string MsgBox_NameDirectory_Title {
            get {
                return ResourceManager.GetString("MsgBox_NameDirectory_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_NameDirectory_Body {
            get {
                return ResourceManager.GetString("MsgBox_NameDirectory_Body", resourceCulture);
            }
        }
        
        public static string MsgBox_RemoveDirectory_Disclaimer {
            get {
                return ResourceManager.GetString("MsgBox_RemoveDirectory_Disclaimer", resourceCulture);
            }
        }
        
        public static string MsgBox_RemoveDocument_Disclaimer {
            get {
                return ResourceManager.GetString("MsgBox_RemoveDocument_Disclaimer", resourceCulture);
            }
        }
        
        public static string MsgBox_NameItem_Label {
            get {
                return ResourceManager.GetString("MsgBox_NameItem_Label", resourceCulture);
            }
        }
        
        public static string MsgBox_NameDocument_Body {
            get {
                return ResourceManager.GetString("MsgBox_NameDocument_Body", resourceCulture);
            }
        }
        
        public static string MsgBox_NameDocument_Title {
            get {
                return ResourceManager.GetString("MsgBox_NameDocument_Title", resourceCulture);
            }
        }
        
        public static string ScriptServiceLocator_Get_UnregisteredScript {
            get {
                return ResourceManager.GetString("ScriptServiceLocator_Get_UnregisteredScript", resourceCulture);
            }
        }
        
        public static string MsgBox_Save_Title {
            get {
                return ResourceManager.GetString("MsgBox_Save_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_Save_Body {
            get {
                return ResourceManager.GetString("MsgBox_Save_Body", resourceCulture);
            }
        }
        
        public static string FileDialog_FileType_Project {
            get {
                return ResourceManager.GetString("FileDialog_FileType_Project", resourceCulture);
            }
        }
        
        public static string FileDialog_OpenProject_Title {
            get {
                return ResourceManager.GetString("FileDialog_OpenProject_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_SaveProject_Title {
            get {
                return ResourceManager.GetString("FileDialog_SaveProject_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_OpenSubtitle_Title {
            get {
                return ResourceManager.GetString("FileDialog_OpenSubtitle_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_FileType_Ass {
            get {
                return ResourceManager.GetString("FileDialog_FileType_Ass", resourceCulture);
            }
        }
        
        public static string FileDialog_FileType_Srt {
            get {
                return ResourceManager.GetString("FileDialog_FileType_Srt", resourceCulture);
            }
        }
        
        public static string FileDialog_SaveSubtitle_Title {
            get {
                return ResourceManager.GetString("FileDialog_SaveSubtitle_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_ExportSubtitle_Title {
            get {
                return ResourceManager.GetString("FileDialog_ExportSubtitle_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_FileType_Text {
            get {
                return ResourceManager.GetString("FileDialog_FileType_Text", resourceCulture);
            }
        }
        
        public static string MsgBox_ScriptService_Title {
            get {
                return ResourceManager.GetString("MsgBox_ScriptService_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_ScriptService_Reload_Body {
            get {
                return ResourceManager.GetString("MsgBox_ScriptService_Reload_Body", resourceCulture);
            }
        }
        
        public static string FileDialog_OpenVideo_Title {
            get {
                return ResourceManager.GetString("FileDialog_OpenVideo_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_FileType_Video {
            get {
                return ResourceManager.GetString("FileDialog_FileType_Video", resourceCulture);
            }
        }
        
        public static string FileDialog_OpenFolderAsProject_Title {
            get {
                return ResourceManager.GetString("FileDialog_OpenFolderAsProject_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_AttachReferenceFile_Title {
            get {
                return ResourceManager.GetString("FileDialog_AttachReferenceFile_Title", resourceCulture);
            }
        }
        
        public static string CrashReporter_WindowTitle {
            get {
                return ResourceManager.GetString("CrashReporter_WindowTitle", resourceCulture);
            }
        }
        
        public static string CrashReporter_Header {
            get {
                return ResourceManager.GetString("CrashReporter_Header", resourceCulture);
            }
        }
        
        public static string CrashReporter_Info {
            get {
                return ResourceManager.GetString("CrashReporter_Info", resourceCulture);
            }
        }
        
        public static string Message_ClipboardEmpty {
            get {
                return ResourceManager.GetString("Message_ClipboardEmpty", resourceCulture);
            }
        }
        
        public static string MsgBox_Btn_OK {
            get {
                return ResourceManager.GetString("MsgBox_Btn_OK", resourceCulture);
            }
        }
        
        public static string MsgBox_Btn_Cancel {
            get {
                return ResourceManager.GetString("MsgBox_Btn_Cancel", resourceCulture);
            }
        }
        
        public static string MsgBox_Btn_Yes {
            get {
                return ResourceManager.GetString("MsgBox_Btn_Yes", resourceCulture);
            }
        }
        
        public static string MsgBox_Btn_No {
            get {
                return ResourceManager.GetString("MsgBox_Btn_No", resourceCulture);
            }
        }
        
        public static string MsgBox_LoadVideo_Title {
            get {
                return ResourceManager.GetString("MsgBox_LoadVideo_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_LoadVideo_Body {
            get {
                return ResourceManager.GetString("MsgBox_LoadVideo_Body", resourceCulture);
            }
        }
        
        public static string Message_VideoNotFound {
            get {
                return ResourceManager.GetString("Message_VideoNotFound", resourceCulture);
            }
        }
        
        public static string Message_SavedFrame {
            get {
                return ResourceManager.GetString("Message_SavedFrame", resourceCulture);
            }
        }
        
        public static string Message_CopiedFrame {
            get {
                return ResourceManager.GetString("Message_CopiedFrame", resourceCulture);
            }
        }
        
        public static string FileDialog_SaveFrame_Title {
            get {
                return ResourceManager.GetString("FileDialog_SaveFrame_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_FileType_Png {
            get {
                return ResourceManager.GetString("FileDialog_FileType_Png", resourceCulture);
            }
        }
        
        public static string Message_UpdateAvailable {
            get {
                return ResourceManager.GetString("Message_UpdateAvailable", resourceCulture);
            }
        }
        
        public static string MsgBox_MediaDisabled_Body {
            get {
                return ResourceManager.GetString("MsgBox_MediaDisabled_Body", resourceCulture);
            }
        }
        
        public static string MsgBox_MediaDisabled_Title {
            get {
                return ResourceManager.GetString("MsgBox_MediaDisabled_Title", resourceCulture);
            }
        }
        
        public static string Message_AutosaveComplete {
            get {
                return ResourceManager.GetString("Message_AutosaveComplete", resourceCulture);
            }
        }
        
        public static string SelectTrackDialog_Title {
            get {
                return ResourceManager.GetString("SelectTrackDialog_Title", resourceCulture);
            }
        }
        
        public static string SelectTrackDialog_Body {
            get {
                return ResourceManager.GetString("SelectTrackDialog_Body", resourceCulture);
            }
        }
        
        public static string SelectTrackDialog_Button_Load {
            get {
                return ResourceManager.GetString("SelectTrackDialog_Button_Load", resourceCulture);
            }
        }
        
        public static string FileDialog_OpenAudio_Title {
            get {
                return ResourceManager.GetString("FileDialog_OpenAudio_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_FileType_Audio {
            get {
                return ResourceManager.GetString("FileDialog_FileType_Audio", resourceCulture);
            }
        }
        
        public static string ChangelogDialog_Title {
            get {
                return ResourceManager.GetString("ChangelogDialog_Title", resourceCulture);
            }
        }
        
        public static string Changelog_NoChangelog {
            get {
                return ResourceManager.GetString("Changelog_NoChangelog", resourceCulture);
            }
        }
        
        public static string Message_AudioAutoloaded {
            get {
                return ResourceManager.GetString("Message_AudioAutoloaded", resourceCulture);
            }
        }
        
        public static string Message_KeyframesNotFound {
            get {
                return ResourceManager.GetString("Message_KeyframesNotFound", resourceCulture);
            }
        }
    }
}
