//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Other {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Other() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.Other", typeof(Other).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string LogWindow_Title {
            get {
                return ResourceManager.GetString("LogWindow_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_RemoveDocument_Title {
            get {
                return ResourceManager.GetString("MsgBox_RemoveDocument_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_RemoveDocument_Body {
            get {
                return ResourceManager.GetString("MsgBox_RemoveDocument_Body", resourceCulture);
            }
        }
        
        public static string MsgBox_RemoveDirectory_Title {
            get {
                return ResourceManager.GetString("MsgBox_RemoveDirectory_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_RemoveDirectory_Body {
            get {
                return ResourceManager.GetString("MsgBox_RemoveDirectory_Body", resourceCulture);
            }
        }
        
        public static string MsgBox_NameDirectory_Title {
            get {
                return ResourceManager.GetString("MsgBox_NameDirectory_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_NameDirectory_Body {
            get {
                return ResourceManager.GetString("MsgBox_NameDirectory_Body", resourceCulture);
            }
        }
        
        public static string MsgBox_NameItem_Label {
            get {
                return ResourceManager.GetString("MsgBox_NameItem_Label", resourceCulture);
            }
        }
        
        public static string MsgBox_NameDocument_Body {
            get {
                return ResourceManager.GetString("MsgBox_NameDocument_Body", resourceCulture);
            }
        }
        
        public static string MsgBox_NameDocument_Title {
            get {
                return ResourceManager.GetString("MsgBox_NameDocument_Title", resourceCulture);
            }
        }
        
        public static string ScriptServiceLocator_Get_UnregisteredScript {
            get {
                return ResourceManager.GetString("ScriptServiceLocator_Get_UnregisteredScript", resourceCulture);
            }
        }
        
        public static string MsgBox_Save_Title {
            get {
                return ResourceManager.GetString("MsgBox_Save_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_Save_Body {
            get {
                return ResourceManager.GetString("MsgBox_Save_Body", resourceCulture);
            }
        }
        
        public static string FileDialog_FileType_Solution {
            get {
                return ResourceManager.GetString("FileDialog_FileType_Solution", resourceCulture);
            }
        }
        
        public static string FileDialog_OpenSolution_Title {
            get {
                return ResourceManager.GetString("FileDialog_OpenSolution_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_SaveSolution_Title {
            get {
                return ResourceManager.GetString("FileDialog_SaveSolution_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_OpenSubtitle_Title {
            get {
                return ResourceManager.GetString("FileDialog_OpenSubtitle_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_FileType_Ass {
            get {
                return ResourceManager.GetString("FileDialog_FileType_Ass", resourceCulture);
            }
        }
        
        public static string FileDialog_SaveSubtitle_Title {
            get {
                return ResourceManager.GetString("FileDialog_SaveSubtitle_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_ExportSubtitle_Title {
            get {
                return ResourceManager.GetString("FileDialog_ExportSubtitle_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_FileType_Text {
            get {
                return ResourceManager.GetString("FileDialog_FileType_Text", resourceCulture);
            }
        }
        
        public static string MsgBox_ScriptService_Title {
            get {
                return ResourceManager.GetString("MsgBox_ScriptService_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_ScriptService_Reload_Body {
            get {
                return ResourceManager.GetString("MsgBox_ScriptService_Reload_Body", resourceCulture);
            }
        }
        
        public static string FileDialog_OpenVideo_Title {
            get {
                return ResourceManager.GetString("FileDialog_OpenVideo_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_FileType_Video {
            get {
                return ResourceManager.GetString("FileDialog_FileType_Video", resourceCulture);
            }
        }
        
        public static string FileDialog_OpenFolderAsSolution_Title {
            get {
                return ResourceManager.GetString("FileDialog_OpenFolderAsSolution_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_AttachReferenceFile_Title {
            get {
                return ResourceManager.GetString("FileDialog_AttachReferenceFile_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_FileModified_Title {
            get {
                return ResourceManager.GetString("MsgBox_FileModified_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_FileModified_Body_L1 {
            get {
                return ResourceManager.GetString("MsgBox_FileModified_Body_L1", resourceCulture);
            }
        }
        
        public static string MsgBox_FileModified_Body_L2 {
            get {
                return ResourceManager.GetString("MsgBox_FileModified_Body_L2", resourceCulture);
            }
        }
    }
}
