//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PasteOver {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PasteOver() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ameko.I18N.PasteOver", typeof(PasteOver).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string PasteOver_Button_All {
            get {
                return ResourceManager.GetString("PasteOver_Button_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all fields.
        /// </summary>
        public static string PasteOver_Button_All_ToolTip {
            get {
                return ResourceManager.GetString("PasteOver_Button_All_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string PasteOver_Button_Confirm {
            get {
                return ResourceManager.GetString("PasteOver_Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string PasteOver_Button_None {
            get {
                return ResourceManager.GetString("PasteOver_Button_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select no fields.
        /// </summary>
        public static string PasteOver_Button_None_ToolTip {
            get {
                return ResourceManager.GetString("PasteOver_Button_None_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string PasteOver_Button_Text {
            get {
                return ResourceManager.GetString("PasteOver_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select only text.
        /// </summary>
        public static string PasteOver_Button_Text_ToolTip {
            get {
                return ResourceManager.GetString("PasteOver_Button_Text_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        public static string PasteOver_Button_Times {
            get {
                return ResourceManager.GetString("PasteOver_Button_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select only start and end time.
        /// </summary>
        public static string PasteOver_Button_Times_ToolTip {
            get {
                return ResourceManager.GetString("PasteOver_Button_Times_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor.
        /// </summary>
        public static string PasteOver_CB_Actor {
            get {
                return ResourceManager.GetString("PasteOver_CB_Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string PasteOver_CB_Comment {
            get {
                return ResourceManager.GetString("PasteOver_CB_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect.
        /// </summary>
        public static string PasteOver_CB_Effect {
            get {
                return ResourceManager.GetString("PasteOver_CB_Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string PasteOver_CB_EndTime {
            get {
                return ResourceManager.GetString("PasteOver_CB_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        public static string PasteOver_CB_Layer {
            get {
                return ResourceManager.GetString("PasteOver_CB_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Margin.
        /// </summary>
        public static string PasteOver_CB_MarginLeft {
            get {
                return ResourceManager.GetString("PasteOver_CB_MarginLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Margin.
        /// </summary>
        public static string PasteOver_CB_MarginRight {
            get {
                return ResourceManager.GetString("PasteOver_CB_MarginRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Margin.
        /// </summary>
        public static string PasteOver_CB_MarginVertical {
            get {
                return ResourceManager.GetString("PasteOver_CB_MarginVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string PasteOver_CB_StartTime {
            get {
                return ResourceManager.GetString("PasteOver_CB_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string PasteOver_CB_Style {
            get {
                return ResourceManager.GetString("PasteOver_CB_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string PasteOver_CB_Text {
            get {
                return ResourceManager.GetString("PasteOver_CB_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select fields to paste over:.
        /// </summary>
        public static string PasteOver_Label_SelectFields {
            get {
                return ResourceManager.GetString("PasteOver_Label_SelectFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Over.
        /// </summary>
        public static string PasteOver_WindowTitle {
            get {
                return ResourceManager.GetString("PasteOver_WindowTitle", resourceCulture);
            }
        }
    }
}
