//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PkgMan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PkgMan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ameko.I18N.PkgMan", typeof(PkgMan).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string PkgMan_Button_AddRepo {
            get {
                return ResourceManager.GetString("PkgMan_Button_AddRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new repository.
        /// </summary>
        public static string PkgMan_Button_AddRepo_ToolTip {
            get {
                return ResourceManager.GetString("PkgMan_Button_AddRepo_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string PkgMan_Button_Install {
            get {
                return ResourceManager.GetString("PkgMan_Button_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the selected module.
        /// </summary>
        public static string PkgMan_Button_Install_ToolTip {
            get {
                return ResourceManager.GetString("PkgMan_Button_Install_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the Module Store.
        /// </summary>
        public static string PkgMan_Button_Refresh_ToolTip {
            get {
                return ResourceManager.GetString("PkgMan_Button_Refresh_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string PkgMan_Button_RemoveRepo {
            get {
                return ResourceManager.GetString("PkgMan_Button_RemoveRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected repository.
        /// </summary>
        public static string PkgMan_Button_RemoveRepo_ToolTip {
            get {
                return ResourceManager.GetString("PkgMan_Button_RemoveRepo_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string PkgMan_Button_Uninstall {
            get {
                return ResourceManager.GetString("PkgMan_Button_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall the selected module.
        /// </summary>
        public static string PkgMan_Button_Uninstall_ToolTip {
            get {
                return ResourceManager.GetString("PkgMan_Button_Uninstall_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string PkgMan_Button_Update {
            get {
                return ResourceManager.GetString("PkgMan_Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the selected module to its latest version.
        /// </summary>
        public static string PkgMan_Button_Update_ToolTip {
            get {
                return ResourceManager.GetString("PkgMan_Button_Update_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update All.
        /// </summary>
        public static string PkgMan_Button_UpdateAll {
            get {
                return ResourceManager.GetString("PkgMan_Button_UpdateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all modules to their latest version.
        /// </summary>
        public static string PkgMan_Button_UpdateAll_ToolTip {
            get {
                return ResourceManager.GetString("PkgMan_Button_UpdateAll_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string PkgMan_Info_Author {
            get {
                return ResourceManager.GetString("PkgMan_Info_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string PkgMan_Info_Dependencies {
            get {
                return ResourceManager.GetString("PkgMan_Info_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PkgMan_Info_Description {
            get {
                return ResourceManager.GetString("PkgMan_Info_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta Channel?.
        /// </summary>
        public static string PkgMan_Info_IsBetaChannel {
            get {
                return ResourceManager.GetString("PkgMan_Info_IsBetaChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintainer.
        /// </summary>
        public static string PkgMan_Info_Maintainer {
            get {
                return ResourceManager.GetString("PkgMan_Info_Maintainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string PkgMan_Info_ModuleCount {
            get {
                return ResourceManager.GetString("PkgMan_Info_ModuleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PkgMan_Info_Name {
            get {
                return ResourceManager.GetString("PkgMan_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Selection.
        /// </summary>
        public static string PkgMan_Info_NoSelection {
            get {
                return ResourceManager.GetString("PkgMan_Info_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualified Name.
        /// </summary>
        public static string PkgMan_Info_QualifiedName {
            get {
                return ResourceManager.GetString("PkgMan_Info_QualifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string PkgMan_Info_Repository {
            get {
                return ResourceManager.GetString("PkgMan_Info_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Repositories.
        /// </summary>
        public static string PkgMan_Info_SubRepoCount {
            get {
                return ResourceManager.GetString("PkgMan_Info_SubRepoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string PkgMan_Info_Type {
            get {
                return ResourceManager.GetString("PkgMan_Info_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string PkgMan_Info_Url {
            get {
                return ResourceManager.GetString("PkgMan_Info_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string PkgMan_Info_Version {
            get {
                return ResourceManager.GetString("PkgMan_Info_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Modules.
        /// </summary>
        public static string PkgMan_InstalledModules {
            get {
                return ResourceManager.GetString("PkgMan_InstalledModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string PkgMan_ModulesTab {
            get {
                return ResourceManager.GetString("PkgMan_ModulesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Store.
        /// </summary>
        public static string PkgMan_ModuleStore {
            get {
                return ResourceManager.GetString("PkgMan_ModuleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh successful.
        /// </summary>
        public static string PkgMan_MsgBox_Refreshed {
            get {
                return ResourceManager.GetString("PkgMan_MsgBox_Refreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        public static string PkgMan_RepositoriesTab {
            get {
                return ResourceManager.GetString("PkgMan_RepositoriesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module is already installed!.
        /// </summary>
        public static string PkgMan_Result_AlreadyInstalled {
            get {
                return ResourceManager.GetString("PkgMan_Result_AlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a required dependency.
        /// </summary>
        public static string PkgMan_Result_DepNotFound {
            get {
                return ResourceManager.GetString("PkgMan_Result_DepNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed!.
        /// </summary>
        public static string PkgMan_Result_Failure {
            get {
                return ResourceManager.GetString("PkgMan_Result_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A filesystem error occured.
        /// </summary>
        public static string PkgMan_Result_FS_Failure {
            get {
                return ResourceManager.GetString("PkgMan_Result_FS_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module has an invalid name.
        /// </summary>
        public static string PkgMan_Result_InvalidName {
            get {
                return ResourceManager.GetString("PkgMan_Result_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This module is required by other modules.
        /// </summary>
        public static string PkgMan_Result_IsRequiredDep {
            get {
                return ResourceManager.GetString("PkgMan_Result_IsRequiredDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module is not installed.
        /// </summary>
        public static string PkgMan_Result_NotInstalled {
            get {
                return ResourceManager.GetString("PkgMan_Result_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repository is already installed!.
        /// </summary>
        public static string PkgMan_Result_Repository_AlreadyInstalled {
            get {
                return ResourceManager.GetString("PkgMan_Result_Repository_AlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repository is not installed.
        /// </summary>
        public static string PkgMan_Result_Repository_NotInstalled {
            get {
                return ResourceManager.GetString("PkgMan_Result_Repository_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string PkgMan_Result_Success {
            get {
                return ResourceManager.GetString("PkgMan_Result_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available for this module.
        /// </summary>
        public static string PkgMan_Update_Available_ToolTip {
            get {
                return ResourceManager.GetString("PkgMan_Update_Available_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ameko Package Manager.
        /// </summary>
        public static string PkgManWindow_Title {
            get {
                return ResourceManager.GetString("PkgManWindow_Title", resourceCulture);
            }
        }
    }
}
