//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PkgMan {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PkgMan() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.PkgMan", typeof(PkgMan).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string PkgManWindow_Title {
            get {
                return ResourceManager.GetString("PkgManWindow_Title", resourceCulture);
            }
        }
        
        public static string PkgMan_PackageStore {
            get {
                return ResourceManager.GetString("PkgMan_PackageStore", resourceCulture);
            }
        }
        
        public static string PkgMan_Info_Name {
            get {
                return ResourceManager.GetString("PkgMan_Info_Name", resourceCulture);
            }
        }
        
        public static string PkgMan_Info_QualifiedName {
            get {
                return ResourceManager.GetString("PkgMan_Info_QualifiedName", resourceCulture);
            }
        }
        
        public static string PkgMan_Info_Version {
            get {
                return ResourceManager.GetString("PkgMan_Info_Version", resourceCulture);
            }
        }
        
        public static string PkgMan_Info_Author {
            get {
                return ResourceManager.GetString("PkgMan_Info_Author", resourceCulture);
            }
        }
        
        public static string PkgMan_Info_Description {
            get {
                return ResourceManager.GetString("PkgMan_Info_Description", resourceCulture);
            }
        }
        
        public static string PkgMan_Info_Dependencies {
            get {
                return ResourceManager.GetString("PkgMan_Info_Dependencies", resourceCulture);
            }
        }
        
        public static string PkgMan_Info_Type {
            get {
                return ResourceManager.GetString("PkgMan_Info_Type", resourceCulture);
            }
        }
        
        public static string PkgMan_Info_NoSelection {
            get {
                return ResourceManager.GetString("PkgMan_Info_NoSelection", resourceCulture);
            }
        }
        
        public static string PkgMan_InstalledPackages {
            get {
                return ResourceManager.GetString("PkgMan_InstalledPackages", resourceCulture);
            }
        }
        
        public static string PkgMan_Info_Repository {
            get {
                return ResourceManager.GetString("PkgMan_Info_Repository", resourceCulture);
            }
        }
        
        public static string PkgMan_RepositoriesTab {
            get {
                return ResourceManager.GetString("PkgMan_RepositoriesTab", resourceCulture);
            }
        }
        
        public static string PkgMan_Button_Install {
            get {
                return ResourceManager.GetString("PkgMan_Button_Install", resourceCulture);
            }
        }
        
        public static string PkgMan_Button_UpdateAll {
            get {
                return ResourceManager.GetString("PkgMan_Button_UpdateAll", resourceCulture);
            }
        }
        
        public static string PkgMan_Button_Update {
            get {
                return ResourceManager.GetString("PkgMan_Button_Update", resourceCulture);
            }
        }
        
        public static string PkgMan_Button_Uninstall {
            get {
                return ResourceManager.GetString("PkgMan_Button_Uninstall", resourceCulture);
            }
        }
        
        public static string PkgMan_Button_Install_ToolTip {
            get {
                return ResourceManager.GetString("PkgMan_Button_Install_ToolTip", resourceCulture);
            }
        }
        
        public static string PkgMan_Button_UpdateAll_ToolTip {
            get {
                return ResourceManager.GetString("PkgMan_Button_UpdateAll_ToolTip", resourceCulture);
            }
        }
        
        public static string PkgMan_Button_Update_ToolTip {
            get {
                return ResourceManager.GetString("PkgMan_Button_Update_ToolTip", resourceCulture);
            }
        }
        
        public static string PkgMan_Button_Uninstall_ToolTip {
            get {
                return ResourceManager.GetString("PkgMan_Button_Uninstall_ToolTip", resourceCulture);
            }
        }
        
        public static string PkgMan_Result_Success {
            get {
                return ResourceManager.GetString("PkgMan_Result_Success", resourceCulture);
            }
        }
        
        public static string PkgMan_Result_Failure {
            get {
                return ResourceManager.GetString("PkgMan_Result_Failure", resourceCulture);
            }
        }
        
        public static string PkgMan_Result_DepNotFound {
            get {
                return ResourceManager.GetString("PkgMan_Result_DepNotFound", resourceCulture);
            }
        }
        
        public static string PkgMan_Result_AlreadyInstalled {
            get {
                return ResourceManager.GetString("PkgMan_Result_AlreadyInstalled", resourceCulture);
            }
        }
        
        public static string PkgMan_Result_NotInstalled {
            get {
                return ResourceManager.GetString("PkgMan_Result_NotInstalled", resourceCulture);
            }
        }
        
        public static string PkgMan_Result_FS_Failure {
            get {
                return ResourceManager.GetString("PkgMan_Result_FS_Failure", resourceCulture);
            }
        }
        
        public static string PkgMan_Result_IsRequiredDep {
            get {
                return ResourceManager.GetString("PkgMan_Result_IsRequiredDep", resourceCulture);
            }
        }
        
        public static string PkgMan_Update_Available_ToolTip {
            get {
                return ResourceManager.GetString("PkgMan_Update_Available_ToolTip", resourceCulture);
            }
        }
        
        public static string PkgMan_Button_Refresh_ToolTip {
            get {
                return ResourceManager.GetString("PkgMan_Button_Refresh_ToolTip", resourceCulture);
            }
        }
        
        public static string PkgMan_MsgBox_Refreshed {
            get {
                return ResourceManager.GetString("PkgMan_MsgBox_Refreshed", resourceCulture);
            }
        }
        
        public static string PkgMan_PackagesTab {
            get {
                return ResourceManager.GetString("PkgMan_PackagesTab", resourceCulture);
            }
        }
        
        public static string PkgMan_Button_RemoveRepo {
            get {
                return ResourceManager.GetString("PkgMan_Button_RemoveRepo", resourceCulture);
            }
        }
        
        public static string PkgMan_Button_AddRepo {
            get {
                return ResourceManager.GetString("PkgMan_Button_AddRepo", resourceCulture);
            }
        }
        
        public static string PkgMan_Button_RemoveRepo_ToolTip {
            get {
                return ResourceManager.GetString("PkgMan_Button_RemoveRepo_ToolTip", resourceCulture);
            }
        }
        
        public static string PkgMan_Button_AddRepo_ToolTip {
            get {
                return ResourceManager.GetString("PkgMan_Button_AddRepo_ToolTip", resourceCulture);
            }
        }
        
        public static string PkgMan_Info_Maintainer {
            get {
                return ResourceManager.GetString("PkgMan_Info_Maintainer", resourceCulture);
            }
        }
        
        public static string PkgMan_Info_IsBetaChannel {
            get {
                return ResourceManager.GetString("PkgMan_Info_IsBetaChannel", resourceCulture);
            }
        }
        
        public static string PkgMan_Info_SubRepoCount {
            get {
                return ResourceManager.GetString("PkgMan_Info_SubRepoCount", resourceCulture);
            }
        }
        
        public static string PkgMan_Info_PackageCount {
            get {
                return ResourceManager.GetString("PkgMan_Info_PackageCount", resourceCulture);
            }
        }
        
        public static string PkgMan_Info_Url {
            get {
                return ResourceManager.GetString("PkgMan_Info_Url", resourceCulture);
            }
        }
        
        public static string PkgMan_Result_Repository_NotInstalled {
            get {
                return ResourceManager.GetString("PkgMan_Result_Repository_NotInstalled", resourceCulture);
            }
        }
        
        public static string PkgMan_Result_Repository_AlreadyInstalled {
            get {
                return ResourceManager.GetString("PkgMan_Result_Repository_AlreadyInstalled", resourceCulture);
            }
        }
        
        public static string PkgMan_Result_InvalidName {
            get {
                return ResourceManager.GetString("PkgMan_Result_InvalidName", resourceCulture);
            }
        }
    }
}
