//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Playground {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Playground() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.Playground", typeof(Playground).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Playground_WindowTitle {
            get {
                return ResourceManager.GetString("Playground_WindowTitle", resourceCulture);
            }
        }
        
        public static string Playground_Status_Ready {
            get {
                return ResourceManager.GetString("Playground_Status_Ready", resourceCulture);
            }
        }
        
        public static string Playground_Status_Success {
            get {
                return ResourceManager.GetString("Playground_Status_Success", resourceCulture);
            }
        }
        
        public static string Playground_Status_Failure {
            get {
                return ResourceManager.GetString("Playground_Status_Failure", resourceCulture);
            }
        }
        
        public static string Playground_Button_Execute {
            get {
                return ResourceManager.GetString("Playground_Button_Execute", resourceCulture);
            }
        }
        
        public static string Playground_Button_Reset {
            get {
                return ResourceManager.GetString("Playground_Button_Reset", resourceCulture);
            }
        }
    }
}
