//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string LogWindow_Title {
            get {
                return ResourceManager.GetString("LogWindow_Title", resourceCulture);
            }
        }
        
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        public static string Menu_Subtitle {
            get {
                return ResourceManager.GetString("Menu_Subtitle", resourceCulture);
            }
        }
        
        public static string Menu_Timing {
            get {
                return ResourceManager.GetString("Menu_Timing", resourceCulture);
            }
        }
        
        public static string Menu_Video {
            get {
                return ResourceManager.GetString("Menu_Video", resourceCulture);
            }
        }
        
        public static string Menu_Scripts {
            get {
                return ResourceManager.GetString("Menu_Scripts", resourceCulture);
            }
        }
        
        public static string Menu_Layouts {
            get {
                return ResourceManager.GetString("Menu_Layouts", resourceCulture);
            }
        }
        
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        public static string Menu_ShowLogs {
            get {
                return ResourceManager.GetString("Menu_ShowLogs", resourceCulture);
            }
        }
        
        public static string SolutionExplorer_Header {
            get {
                return ResourceManager.GetString("SolutionExplorer_Header", resourceCulture);
            }
        }
        
        public static string Toolbox_Header {
            get {
                return ResourceManager.GetString("Toolbox_Header", resourceCulture);
            }
        }
        
        public static string EventsGrid_Header_Start {
            get {
                return ResourceManager.GetString("EventsGrid_Header_Start", resourceCulture);
            }
        }
        
        public static string EventsGrid_Header_End {
            get {
                return ResourceManager.GetString("EventsGrid_Header_End", resourceCulture);
            }
        }
        
        public static string EventsGrid_Header_Cps {
            get {
                return ResourceManager.GetString("EventsGrid_Header_Cps", resourceCulture);
            }
        }
        
        public static string EventsGrid_Header_Style {
            get {
                return ResourceManager.GetString("EventsGrid_Header_Style", resourceCulture);
            }
        }
        
        public static string EventsGrid_Header_Actor {
            get {
                return ResourceManager.GetString("EventsGrid_Header_Actor", resourceCulture);
            }
        }
        
        public static string EventsGrid_Header_Effect {
            get {
                return ResourceManager.GetString("EventsGrid_Header_Effect", resourceCulture);
            }
        }
        
        public static string EventsGrid_Header_Content {
            get {
                return ResourceManager.GetString("EventsGrid_Header_Content", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_Duplicate {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_Duplicate", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_MergeLines {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_MergeLines", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_SplitLine {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_SplitLine", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_InsertBefore {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_InsertBefore", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_InsertAfter {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_InsertAfter", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_Copy {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_Copy", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_Paste {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_Paste", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_PasteOver {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_PasteOver", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_Delete {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_Delete", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_Cut {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_Cut", resourceCulture);
            }
        }
        
        public static string Editor_IsComment_Label {
            get {
                return ResourceManager.GetString("Editor_IsComment_Label", resourceCulture);
            }
        }
        
        public static string Editor_IsComment_ToolTip {
            get {
                return ResourceManager.GetString("Editor_IsComment_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_StyleBox_ToolTip {
            get {
                return ResourceManager.GetString("Editor_StyleBox_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_EditStyle_ToolTip {
            get {
                return ResourceManager.GetString("Editor_EditStyle_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_ActorAcBox_Watermark {
            get {
                return ResourceManager.GetString("Editor_ActorAcBox_Watermark", resourceCulture);
            }
        }
        
        public static string Editor_ActorAcBox_ToolTip {
            get {
                return ResourceManager.GetString("Editor_ActorAcBox_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_EffectAcBox_Watermark {
            get {
                return ResourceManager.GetString("Editor_EffectAcBox_Watermark", resourceCulture);
            }
        }
        
        public static string Editor_EffectAcBox_ToolTip {
            get {
                return ResourceManager.GetString("Editor_EffectAcBox_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_MaxLineWidth_ToolTip {
            get {
                return ResourceManager.GetString("Editor_MaxLineWidth_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_LayerUpDown_ToolTip {
            get {
                return ResourceManager.GetString("Editor_LayerUpDown_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_StartBox_ToolTip {
            get {
                return ResourceManager.GetString("Editor_StartBox_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_EndBox_ToolTip {
            get {
                return ResourceManager.GetString("Editor_EndBox_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_MarginLeft_ToolTip {
            get {
                return ResourceManager.GetString("Editor_MarginLeft_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_MarginRight_ToolTip {
            get {
                return ResourceManager.GetString("Editor_MarginRight_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_MarginVertical_ToolTip {
            get {
                return ResourceManager.GetString("Editor_MarginVertical_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_ToggleBold_ToolTip {
            get {
                return ResourceManager.GetString("Editor_ToggleBold_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_ToggleItalics_ToolTip {
            get {
                return ResourceManager.GetString("Editor_ToggleItalics_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_ToggleUnderline_ToolTip {
            get {
                return ResourceManager.GetString("Editor_ToggleUnderline_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_ToggleStrikethrough_ToolTip {
            get {
                return ResourceManager.GetString("Editor_ToggleStrikethrough_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_SetFont_ToolTip {
            get {
                return ResourceManager.GetString("Editor_SetFont_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_NextOrCreate_ToolTip {
            get {
                return ResourceManager.GetString("Editor_NextOrCreate_ToolTip", resourceCulture);
            }
        }
        
        public static string Menu_New {
            get {
                return ResourceManager.GetString("Menu_New", resourceCulture);
            }
        }
        
        public static string Menu_OpenSubtitle {
            get {
                return ResourceManager.GetString("Menu_OpenSubtitle", resourceCulture);
            }
        }
        
        public static string Menu_SaveSubtitle {
            get {
                return ResourceManager.GetString("Menu_SaveSubtitle", resourceCulture);
            }
        }
        
        public static string Menu_SaveSubtitleAs {
            get {
                return ResourceManager.GetString("Menu_SaveSubtitleAs", resourceCulture);
            }
        }
        
        public static string Menu_ExportSubtitles {
            get {
                return ResourceManager.GetString("Menu_ExportSubtitles", resourceCulture);
            }
        }
        
        public static string Menu_OpenSolution {
            get {
                return ResourceManager.GetString("Menu_OpenSolution", resourceCulture);
            }
        }
        
        public static string Menu_SaveSolution {
            get {
                return ResourceManager.GetString("Menu_SaveSolution", resourceCulture);
            }
        }
        
        public static string Menu_Quit {
            get {
                return ResourceManager.GetString("Menu_Quit", resourceCulture);
            }
        }
        
        public static string Menu_Undo {
            get {
                return ResourceManager.GetString("Menu_Undo", resourceCulture);
            }
        }
        
        public static string Menu_Redo {
            get {
                return ResourceManager.GetString("Menu_Redo", resourceCulture);
            }
        }
        
        public static string Menu_Search {
            get {
                return ResourceManager.GetString("Menu_Search", resourceCulture);
            }
        }
        
        public static string Menu_StylesManager {
            get {
                return ResourceManager.GetString("Menu_StylesManager", resourceCulture);
            }
        }
        
        public static string Menu_ScriptProperties {
            get {
                return ResourceManager.GetString("Menu_ScriptProperties", resourceCulture);
            }
        }
        
        public static string Menu_Solution {
            get {
                return ResourceManager.GetString("Menu_Solution", resourceCulture);
            }
        }
        
        public static string Menu_SolutionConfig {
            get {
                return ResourceManager.GetString("Menu_SolutionConfig", resourceCulture);
            }
        }
        
        public static string Menu_ShiftTimes {
            get {
                return ResourceManager.GetString("Menu_ShiftTimes", resourceCulture);
            }
        }
        
        public static string Menu_OpenVideo {
            get {
                return ResourceManager.GetString("Menu_OpenVideo", resourceCulture);
            }
        }
        
        public static string Menu_JumpTo {
            get {
                return ResourceManager.GetString("Menu_JumpTo", resourceCulture);
            }
        }
        
        public static string Menu_Configuration {
            get {
                return ResourceManager.GetString("Menu_Configuration", resourceCulture);
            }
        }
        
        public static string Menu_Keybinds {
            get {
                return ResourceManager.GetString("Menu_Keybinds", resourceCulture);
            }
        }
        
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        public static string AboutWindow_GeneralTab {
            get {
                return ResourceManager.GetString("AboutWindow_GeneralTab", resourceCulture);
            }
        }
        
        public static string AboutWindow_AssetsTab {
            get {
                return ResourceManager.GetString("AboutWindow_AssetsTab", resourceCulture);
            }
        }
        
        public static string AboutWindow_LibrariesTab {
            get {
                return ResourceManager.GetString("AboutWindow_LibrariesTab", resourceCulture);
            }
        }
        
        public static string SolutionExplorer_ContextMenu_Remove {
            get {
                return ResourceManager.GetString("SolutionExplorer_ContextMenu_Remove", resourceCulture);
            }
        }
        
        public static string SolutionExplorer_ContextMenu_Open {
            get {
                return ResourceManager.GetString("SolutionExplorer_ContextMenu_Open", resourceCulture);
            }
        }
        
        public static string FileDialog_OpenSubtitle_Title {
            get {
                return ResourceManager.GetString("FileDialog_OpenSubtitle_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_FileType_Ass {
            get {
                return ResourceManager.GetString("FileDialog_FileType_Ass", resourceCulture);
            }
        }
        
        public static string FileDialog_SaveSubtitle_Title {
            get {
                return ResourceManager.GetString("FileDialog_SaveSubtitle_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_ExportSubtitle_Title {
            get {
                return ResourceManager.GetString("FileDialog_ExportSubtitle_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_FileType_Text {
            get {
                return ResourceManager.GetString("FileDialog_FileType_Text", resourceCulture);
            }
        }
        
        public static string Menu_CloseTab {
            get {
                return ResourceManager.GetString("Menu_CloseTab", resourceCulture);
            }
        }
        
        public static string Menu_CloseSolution {
            get {
                return ResourceManager.GetString("Menu_CloseSolution", resourceCulture);
            }
        }
        
        public static string MsgBox_Save_Title {
            get {
                return ResourceManager.GetString("MsgBox_Save_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_Save_Body {
            get {
                return ResourceManager.GetString("MsgBox_Save_Body", resourceCulture);
            }
        }
        
        public static string Tab_CloseButton_ToolTip {
            get {
                return ResourceManager.GetString("Tab_CloseButton_ToolTip", resourceCulture);
            }
        }
        
        public static string FileDialog_FileType_Solution {
            get {
                return ResourceManager.GetString("FileDialog_FileType_Solution", resourceCulture);
            }
        }
        
        public static string FileDialog_OpenSolution_Title {
            get {
                return ResourceManager.GetString("FileDialog_OpenSolution_Title", resourceCulture);
            }
        }
        
        public static string FileDialog_SaveSolution_Title {
            get {
                return ResourceManager.GetString("FileDialog_SaveSolution_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_RemoveDocument_Title {
            get {
                return ResourceManager.GetString("MsgBox_RemoveDocument_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_RemoveDocument_Body {
            get {
                return ResourceManager.GetString("MsgBox_RemoveDocument_Body", resourceCulture);
            }
        }
        
        public static string MsgBox_RemoveDirectory_Title {
            get {
                return ResourceManager.GetString("MsgBox_RemoveDirectory_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_RemoveDirectory_Body {
            get {
                return ResourceManager.GetString("MsgBox_RemoveDirectory_Body", resourceCulture);
            }
        }
        
        public static string StylesManager_Title {
            get {
                return ResourceManager.GetString("StylesManager_Title", resourceCulture);
            }
        }
        
        public static string StylesManager_GlobalStyles {
            get {
                return ResourceManager.GetString("StylesManager_GlobalStyles", resourceCulture);
            }
        }
        
        public static string StylesManager_SolutionStyles {
            get {
                return ResourceManager.GetString("StylesManager_SolutionStyles", resourceCulture);
            }
        }
        
        public static string StylesManager_DocumentStyles {
            get {
                return ResourceManager.GetString("StylesManager_DocumentStyles", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_Delete {
            get {
                return ResourceManager.GetString("StylesManager_Button_Delete", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_Copy {
            get {
                return ResourceManager.GetString("StylesManager_Button_Copy", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_Edit {
            get {
                return ResourceManager.GetString("StylesManager_Button_Edit", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_New {
            get {
                return ResourceManager.GetString("StylesManager_Button_New", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_CopyToSolution {
            get {
                return ResourceManager.GetString("StylesManager_Button_CopyToSolution", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_CopyToGlobal {
            get {
                return ResourceManager.GetString("StylesManager_Button_CopyToGlobal", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_CopyToDocument {
            get {
                return ResourceManager.GetString("StylesManager_Button_CopyToDocument", resourceCulture);
            }
        }
        
        public static string MsgBox_NameDirectory_Title {
            get {
                return ResourceManager.GetString("MsgBox_NameDirectory_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_NameDirectory_Body {
            get {
                return ResourceManager.GetString("MsgBox_NameDirectory_Body", resourceCulture);
            }
        }
        
        public static string MsgBox_NameItem_Label {
            get {
                return ResourceManager.GetString("MsgBox_NameItem_Label", resourceCulture);
            }
        }
        
        public static string SolutionExplorer_ContextMenu_Rename {
            get {
                return ResourceManager.GetString("SolutionExplorer_ContextMenu_Rename", resourceCulture);
            }
        }
        
        public static string MsgBox_NameDocument_Body {
            get {
                return ResourceManager.GetString("MsgBox_NameDocument_Body", resourceCulture);
            }
        }
        
        public static string MsgBox_NameDocument_Title {
            get {
                return ResourceManager.GetString("MsgBox_NameDocument_Title", resourceCulture);
            }
        }
        
        public static string StylesManager_CopyAppendage {
            get {
                return ResourceManager.GetString("StylesManager_CopyAppendage", resourceCulture);
            }
        }
        
        public static string Menu_ReloadScripts {
            get {
                return ResourceManager.GetString("Menu_ReloadScripts", resourceCulture);
            }
        }
        
        public static string Menu_DependencyControl {
            get {
                return ResourceManager.GetString("Menu_DependencyControl", resourceCulture);
            }
        }
        
        public static string MsgBox_ScriptService_Title {
            get {
                return ResourceManager.GetString("MsgBox_ScriptService_Title", resourceCulture);
            }
        }
        
        public static string MsgBox_ScriptService_Reload_Body {
            get {
                return ResourceManager.GetString("MsgBox_ScriptService_Reload_Body", resourceCulture);
            }
        }
        
        public static string DepCtrlWindow_Title {
            get {
                return ResourceManager.GetString("DepCtrlWindow_Title", resourceCulture);
            }
        }
        
        public static string DepCtrl_ModuleStore {
            get {
                return ResourceManager.GetString("DepCtrl_ModuleStore", resourceCulture);
            }
        }
        
        public static string DepCtrl_Info_Name {
            get {
                return ResourceManager.GetString("DepCtrl_Info_Name", resourceCulture);
            }
        }
        
        public static string DepCtrl_Info_QualifiedName {
            get {
                return ResourceManager.GetString("DepCtrl_Info_QualifiedName", resourceCulture);
            }
        }
        
        public static string DepCtrl_Info_Version {
            get {
                return ResourceManager.GetString("DepCtrl_Info_Version", resourceCulture);
            }
        }
        
        public static string DepCtrl_Info_Author {
            get {
                return ResourceManager.GetString("DepCtrl_Info_Author", resourceCulture);
            }
        }
        
        public static string DepCtrl_Info_Description {
            get {
                return ResourceManager.GetString("DepCtrl_Info_Description", resourceCulture);
            }
        }
        
        public static string DepCtrl_Info_Dependencies {
            get {
                return ResourceManager.GetString("DepCtrl_Info_Dependencies", resourceCulture);
            }
        }
        
        public static string DepCtrl_Info_Type {
            get {
                return ResourceManager.GetString("DepCtrl_Info_Type", resourceCulture);
            }
        }
        
        public static string DepCtrl_Info_NoSelection {
            get {
                return ResourceManager.GetString("DepCtrl_Info_NoSelection", resourceCulture);
            }
        }
        
        public static string DepCtrl_InstalledModules {
            get {
                return ResourceManager.GetString("DepCtrl_InstalledModules", resourceCulture);
            }
        }
        
        public static string DepCtrl_Info_Repository {
            get {
                return ResourceManager.GetString("DepCtrl_Info_Repository", resourceCulture);
            }
        }
        
        public static string DepCtrl_RepositoriesTab {
            get {
                return ResourceManager.GetString("DepCtrl_RepositoriesTab", resourceCulture);
            }
        }
        
        public static string DepCtrl_Button_Install {
            get {
                return ResourceManager.GetString("DepCtrl_Button_Install", resourceCulture);
            }
        }
        
        public static string DepCtrl_Button_UpdateAll {
            get {
                return ResourceManager.GetString("DepCtrl_Button_UpdateAll", resourceCulture);
            }
        }
        
        public static string DepCtrl_Button_Update {
            get {
                return ResourceManager.GetString("DepCtrl_Button_Update", resourceCulture);
            }
        }
        
        public static string DepCtrl_Button_Uninstall {
            get {
                return ResourceManager.GetString("DepCtrl_Button_Uninstall", resourceCulture);
            }
        }
        
        public static string DepCtrl_Button_Install_ToolTip {
            get {
                return ResourceManager.GetString("DepCtrl_Button_Install_ToolTip", resourceCulture);
            }
        }
        
        public static string DepCtrl_Button_UpdateAll_ToolTip {
            get {
                return ResourceManager.GetString("DepCtrl_Button_UpdateAll_ToolTip", resourceCulture);
            }
        }
        
        public static string DepCtrl_Button_Update_ToolTip {
            get {
                return ResourceManager.GetString("DepCtrl_Button_Update_ToolTip", resourceCulture);
            }
        }
        
        public static string DepCtrl_Button_Uninstall_ToolTip {
            get {
                return ResourceManager.GetString("DepCtrl_Button_Uninstall_ToolTip", resourceCulture);
            }
        }
        
        public static string DepCtrl_Result_Success {
            get {
                return ResourceManager.GetString("DepCtrl_Result_Success", resourceCulture);
            }
        }
        
        public static string DepCtrl_Result_Failure {
            get {
                return ResourceManager.GetString("DepCtrl_Result_Failure", resourceCulture);
            }
        }
        
        public static string DepCtrl_Result_DepNotFound {
            get {
                return ResourceManager.GetString("DepCtrl_Result_DepNotFound", resourceCulture);
            }
        }
        
        public static string DepCtrl_Result_AlreadyInstalled {
            get {
                return ResourceManager.GetString("DepCtrl_Result_AlreadyInstalled", resourceCulture);
            }
        }
        
        public static string DepCtrl_Result_NotInstalled {
            get {
                return ResourceManager.GetString("DepCtrl_Result_NotInstalled", resourceCulture);
            }
        }
        
        public static string DepCtrl_Result_FS_Failure {
            get {
                return ResourceManager.GetString("DepCtrl_Result_FS_Failure", resourceCulture);
            }
        }
        
        public static string DepCtrl_Result_IsRequiredDep {
            get {
                return ResourceManager.GetString("DepCtrl_Result_IsRequiredDep", resourceCulture);
            }
        }
        
        public static string DepCtrl_Update_Available_ToolTip {
            get {
                return ResourceManager.GetString("DepCtrl_Update_Available_ToolTip", resourceCulture);
            }
        }
        
        public static string DepCtrl_Button_Refresh_ToolTip {
            get {
                return ResourceManager.GetString("DepCtrl_Button_Refresh_ToolTip", resourceCulture);
            }
        }
        
        public static string DepCtrl_MsgBox_Refreshed {
            get {
                return ResourceManager.GetString("DepCtrl_MsgBox_Refreshed", resourceCulture);
            }
        }
        
        public static string DepCtrl_ModulesTab {
            get {
                return ResourceManager.GetString("DepCtrl_ModulesTab", resourceCulture);
            }
        }
        
        public static string DepCtrl_Button_RemoveRepo {
            get {
                return ResourceManager.GetString("DepCtrl_Button_RemoveRepo", resourceCulture);
            }
        }
        
        public static string DepCtrl_Button_AddRepo {
            get {
                return ResourceManager.GetString("DepCtrl_Button_AddRepo", resourceCulture);
            }
        }
        
        public static string DepCtrl_Button_RemoveRepo_ToolTip {
            get {
                return ResourceManager.GetString("DepCtrl_Button_RemoveRepo_ToolTip", resourceCulture);
            }
        }
        
        public static string DepCtrl_Button_AddRepo_ToolTip {
            get {
                return ResourceManager.GetString("DepCtrl_Button_AddRepo_ToolTip", resourceCulture);
            }
        }
        
        public static string DepCtrl_Info_Maintainer {
            get {
                return ResourceManager.GetString("DepCtrl_Info_Maintainer", resourceCulture);
            }
        }
        
        public static string DepCtrl_Info_IsBetaChannel {
            get {
                return ResourceManager.GetString("DepCtrl_Info_IsBetaChannel", resourceCulture);
            }
        }
        
        public static string DepCtrl_Info_SubRepoCount {
            get {
                return ResourceManager.GetString("DepCtrl_Info_SubRepoCount", resourceCulture);
            }
        }
        
        public static string DepCtrl_Info_ModuleCount {
            get {
                return ResourceManager.GetString("DepCtrl_Info_ModuleCount", resourceCulture);
            }
        }
        
        public static string DepCtrl_Info_Url {
            get {
                return ResourceManager.GetString("DepCtrl_Info_Url", resourceCulture);
            }
        }
        
        public static string DepCtrl_Result_Repository_NotInstalled {
            get {
                return ResourceManager.GetString("DepCtrl_Result_Repository_NotInstalled", resourceCulture);
            }
        }
        
        public static string DepCtrl_Result_Repository_AlreadyInstalled {
            get {
                return ResourceManager.GetString("DepCtrl_Result_Repository_AlreadyInstalled", resourceCulture);
            }
        }
    }
}
