//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        public static string Menu_Subtitle {
            get {
                return ResourceManager.GetString("Menu_Subtitle", resourceCulture);
            }
        }
        
        public static string Menu_Timing {
            get {
                return ResourceManager.GetString("Menu_Timing", resourceCulture);
            }
        }
        
        public static string Menu_Video {
            get {
                return ResourceManager.GetString("Menu_Video", resourceCulture);
            }
        }
        
        public static string Menu_Scripts {
            get {
                return ResourceManager.GetString("Menu_Scripts", resourceCulture);
            }
        }
        
        public static string Menu_Layouts {
            get {
                return ResourceManager.GetString("Menu_Layouts", resourceCulture);
            }
        }
        
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        public static string Menu_ShowLogs {
            get {
                return ResourceManager.GetString("Menu_ShowLogs", resourceCulture);
            }
        }
        
        public static string ProjectExplorer_Header {
            get {
                return ResourceManager.GetString("ProjectExplorer_Header", resourceCulture);
            }
        }
        
        public static string Toolbox_Header {
            get {
                return ResourceManager.GetString("Toolbox_Header", resourceCulture);
            }
        }
        
        public static string EventsGrid_Header_Start {
            get {
                return ResourceManager.GetString("EventsGrid_Header_Start", resourceCulture);
            }
        }
        
        public static string EventsGrid_Header_End {
            get {
                return ResourceManager.GetString("EventsGrid_Header_End", resourceCulture);
            }
        }
        
        public static string EventsGrid_Header_Cps {
            get {
                return ResourceManager.GetString("EventsGrid_Header_Cps", resourceCulture);
            }
        }
        
        public static string EventsGrid_Header_Style {
            get {
                return ResourceManager.GetString("EventsGrid_Header_Style", resourceCulture);
            }
        }
        
        public static string EventsGrid_Header_Actor {
            get {
                return ResourceManager.GetString("EventsGrid_Header_Actor", resourceCulture);
            }
        }
        
        public static string EventsGrid_Header_Effect {
            get {
                return ResourceManager.GetString("EventsGrid_Header_Effect", resourceCulture);
            }
        }
        
        public static string EventsGrid_Header_Content {
            get {
                return ResourceManager.GetString("EventsGrid_Header_Content", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_Duplicate {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_Duplicate", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_MergeLines {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_MergeLines", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_SplitLine {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_SplitLine", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_InsertBefore {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_InsertBefore", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_InsertAfter {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_InsertAfter", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_Copy {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_Copy", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_Paste {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_Paste", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_PasteOver {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_PasteOver", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_Delete {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_Delete", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_Cut {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_Cut", resourceCulture);
            }
        }
        
        public static string Editor_IsComment_Label {
            get {
                return ResourceManager.GetString("Editor_IsComment_Label", resourceCulture);
            }
        }
        
        public static string Editor_IsComment_ToolTip {
            get {
                return ResourceManager.GetString("Editor_IsComment_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_StyleBox_ToolTip {
            get {
                return ResourceManager.GetString("Editor_StyleBox_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_EditStyle_ToolTip {
            get {
                return ResourceManager.GetString("Editor_EditStyle_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_ActorAcBox_Watermark {
            get {
                return ResourceManager.GetString("Editor_ActorAcBox_Watermark", resourceCulture);
            }
        }
        
        public static string Editor_ActorAcBox_ToolTip {
            get {
                return ResourceManager.GetString("Editor_ActorAcBox_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_EffectAcBox_Watermark {
            get {
                return ResourceManager.GetString("Editor_EffectAcBox_Watermark", resourceCulture);
            }
        }
        
        public static string Editor_EffectAcBox_ToolTip {
            get {
                return ResourceManager.GetString("Editor_EffectAcBox_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_MaxLineWidth_ToolTip {
            get {
                return ResourceManager.GetString("Editor_MaxLineWidth_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_LayerUpDown_ToolTip {
            get {
                return ResourceManager.GetString("Editor_LayerUpDown_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_StartBox_ToolTip {
            get {
                return ResourceManager.GetString("Editor_StartBox_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_EndBox_ToolTip {
            get {
                return ResourceManager.GetString("Editor_EndBox_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_MarginLeft_ToolTip {
            get {
                return ResourceManager.GetString("Editor_MarginLeft_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_MarginRight_ToolTip {
            get {
                return ResourceManager.GetString("Editor_MarginRight_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_MarginVertical_ToolTip {
            get {
                return ResourceManager.GetString("Editor_MarginVertical_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_ToggleBold_ToolTip {
            get {
                return ResourceManager.GetString("Editor_ToggleBold_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_ToggleItalics_ToolTip {
            get {
                return ResourceManager.GetString("Editor_ToggleItalics_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_ToggleUnderline_ToolTip {
            get {
                return ResourceManager.GetString("Editor_ToggleUnderline_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_ToggleStrikethrough_ToolTip {
            get {
                return ResourceManager.GetString("Editor_ToggleStrikethrough_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_SetFont_ToolTip {
            get {
                return ResourceManager.GetString("Editor_SetFont_ToolTip", resourceCulture);
            }
        }
        
        public static string Editor_NextOrCreate_ToolTip {
            get {
                return ResourceManager.GetString("Editor_NextOrCreate_ToolTip", resourceCulture);
            }
        }
        
        public static string Menu_New {
            get {
                return ResourceManager.GetString("Menu_New", resourceCulture);
            }
        }
        
        public static string Menu_OpenSubtitle {
            get {
                return ResourceManager.GetString("Menu_OpenSubtitle", resourceCulture);
            }
        }
        
        public static string Menu_SaveSubtitle {
            get {
                return ResourceManager.GetString("Menu_SaveSubtitle", resourceCulture);
            }
        }
        
        public static string Menu_SaveSubtitleAs {
            get {
                return ResourceManager.GetString("Menu_SaveSubtitleAs", resourceCulture);
            }
        }
        
        public static string Menu_ExportSubtitles {
            get {
                return ResourceManager.GetString("Menu_ExportSubtitles", resourceCulture);
            }
        }
        
        public static string Menu_OpenProject {
            get {
                return ResourceManager.GetString("Menu_OpenProject", resourceCulture);
            }
        }
        
        public static string Menu_SaveProject {
            get {
                return ResourceManager.GetString("Menu_SaveProject", resourceCulture);
            }
        }
        
        public static string Menu_Quit {
            get {
                return ResourceManager.GetString("Menu_Quit", resourceCulture);
            }
        }
        
        public static string Menu_Undo {
            get {
                return ResourceManager.GetString("Menu_Undo", resourceCulture);
            }
        }
        
        public static string Menu_Redo {
            get {
                return ResourceManager.GetString("Menu_Redo", resourceCulture);
            }
        }
        
        public static string Menu_Search {
            get {
                return ResourceManager.GetString("Menu_Search", resourceCulture);
            }
        }
        
        public static string Menu_StylesManager {
            get {
                return ResourceManager.GetString("Menu_StylesManager", resourceCulture);
            }
        }
        
        public static string Menu_ScriptProperties {
            get {
                return ResourceManager.GetString("Menu_ScriptProperties", resourceCulture);
            }
        }
        
        public static string Menu_Project {
            get {
                return ResourceManager.GetString("Menu_Project", resourceCulture);
            }
        }
        
        public static string Menu_ProjectConfig {
            get {
                return ResourceManager.GetString("Menu_ProjectConfig", resourceCulture);
            }
        }
        
        public static string Menu_ShiftTimes {
            get {
                return ResourceManager.GetString("Menu_ShiftTimes", resourceCulture);
            }
        }
        
        public static string Menu_OpenVideo {
            get {
                return ResourceManager.GetString("Menu_OpenVideo", resourceCulture);
            }
        }
        
        public static string Menu_JumpTo {
            get {
                return ResourceManager.GetString("Menu_JumpTo", resourceCulture);
            }
        }
        
        public static string Menu_Configuration {
            get {
                return ResourceManager.GetString("Menu_Configuration", resourceCulture);
            }
        }
        
        public static string Menu_Keybinds {
            get {
                return ResourceManager.GetString("Menu_Keybinds", resourceCulture);
            }
        }
        
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        public static string ProjectExplorer_ContextMenu_Remove {
            get {
                return ResourceManager.GetString("ProjectExplorer_ContextMenu_Remove", resourceCulture);
            }
        }
        
        public static string ProjectExplorer_ContextMenu_Open {
            get {
                return ResourceManager.GetString("ProjectExplorer_ContextMenu_Open", resourceCulture);
            }
        }
        
        public static string Menu_CloseTab {
            get {
                return ResourceManager.GetString("Menu_CloseTab", resourceCulture);
            }
        }
        
        public static string Menu_CloseProject {
            get {
                return ResourceManager.GetString("Menu_CloseProject", resourceCulture);
            }
        }
        
        public static string Tab_CloseButton_ToolTip {
            get {
                return ResourceManager.GetString("Tab_CloseButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ProjectExplorer_ContextMenu_ChangeDisplayName {
            get {
                return ResourceManager.GetString("ProjectExplorer_ContextMenu_ChangeDisplayName", resourceCulture);
            }
        }
        
        public static string Menu_ReloadScripts {
            get {
                return ResourceManager.GetString("Menu_ReloadScripts", resourceCulture);
            }
        }
        
        public static string Menu_PackageManager {
            get {
                return ResourceManager.GetString("Menu_PackageManager", resourceCulture);
            }
        }
        
        public static string Menu_OpenProjectFolder {
            get {
                return ResourceManager.GetString("Menu_OpenProjectFolder", resourceCulture);
            }
        }
        
        public static string Menu_ReloadLayouts {
            get {
                return ResourceManager.GetString("Menu_ReloadLayouts", resourceCulture);
            }
        }
        
        public static string Video_Button_PlayPause_ToolTip {
            get {
                return ResourceManager.GetString("Video_Button_PlayPause_ToolTip", resourceCulture);
            }
        }
        
        public static string Video_Button_PlaySelection_ToolTip {
            get {
                return ResourceManager.GetString("Video_Button_PlaySelection_ToolTip", resourceCulture);
            }
        }
        
        public static string Video_Button_EnableAutoSeek_ToolTip {
            get {
                return ResourceManager.GetString("Video_Button_EnableAutoSeek_ToolTip", resourceCulture);
            }
        }
        
        public static string Video_Button_DisableAutoSeek_ToolTip {
            get {
                return ResourceManager.GetString("Video_Button_DisableAutoSeek_ToolTip", resourceCulture);
            }
        }
        
        public static string Video_Time_ToolTip {
            get {
                return ResourceManager.GetString("Video_Time_ToolTip", resourceCulture);
            }
        }
        
        public static string Video_Frame_ToolTip {
            get {
                return ResourceManager.GetString("Video_Frame_ToolTip", resourceCulture);
            }
        }
        
        public static string Video_LockAR {
            get {
                return ResourceManager.GetString("Video_LockAR", resourceCulture);
            }
        }
        
        public static string Video_LockAR_ToolTip {
            get {
                return ResourceManager.GetString("Video_LockAR_ToolTip", resourceCulture);
            }
        }
        
        public static string Menu_ReferenceFile_Attach {
            get {
                return ResourceManager.GetString("Menu_ReferenceFile_Attach", resourceCulture);
            }
        }
        
        public static string Menu_ReferenceFile_Detatch {
            get {
                return ResourceManager.GetString("Menu_ReferenceFile_Detatch", resourceCulture);
            }
        }
        
        public static string Menu_Spellcheck {
            get {
                return ResourceManager.GetString("Menu_Spellcheck", resourceCulture);
            }
        }
        
        public static string Menu_Playground {
            get {
                return ResourceManager.GetString("Menu_Playground", resourceCulture);
            }
        }
        
        public static string Message_Welcome {
            get {
                return ResourceManager.GetString("Message_Welcome", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_SplitLineKeepTimes {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_SplitLineKeepTimes", resourceCulture);
            }
        }
        
        public static string Tab_NothingLoaded {
            get {
                return ResourceManager.GetString("Tab_NothingLoaded", resourceCulture);
            }
        }
        
        public static string EventsGrid_Menu_CopyPlaintext {
            get {
                return ResourceManager.GetString("EventsGrid_Menu_CopyPlaintext", resourceCulture);
            }
        }
        
        public static string ProjectExplorer_ContextMenu_AttachAsReference {
            get {
                return ResourceManager.GetString("ProjectExplorer_ContextMenu_AttachAsReference", resourceCulture);
            }
        }
        
        public static string Video_Angle {
            get {
                return ResourceManager.GetString("Video_Angle", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string Error_FailedToParse {
            get {
                return ResourceManager.GetString("Error_FailedToParse", resourceCulture);
            }
        }
        
        public static string Video_ContextMenu_Copy_Frame {
            get {
                return ResourceManager.GetString("Video_ContextMenu_Copy_Frame", resourceCulture);
            }
        }
        
        public static string Video_ContextMenu_Copy_VideoOnly {
            get {
                return ResourceManager.GetString("Video_ContextMenu_Copy_VideoOnly", resourceCulture);
            }
        }
        
        public static string Video_ContextMenu_Copy_SubsOnly {
            get {
                return ResourceManager.GetString("Video_ContextMenu_Copy_SubsOnly", resourceCulture);
            }
        }
        
        public static string Video_ContextMenu_Save_Frame {
            get {
                return ResourceManager.GetString("Video_ContextMenu_Save_Frame", resourceCulture);
            }
        }
        
        public static string Video_ContextMenu_Save_VideoOnly {
            get {
                return ResourceManager.GetString("Video_ContextMenu_Save_VideoOnly", resourceCulture);
            }
        }
        
        public static string Video_ContextMenu_Save_SubsOnly {
            get {
                return ResourceManager.GetString("Video_ContextMenu_Save_SubsOnly", resourceCulture);
            }
        }
    }
}
