//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Search {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Search() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.Search", typeof(Search).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SearchWindow_Title {
            get {
                return ResourceManager.GetString("SearchWindow_Title", resourceCulture);
            }
        }
        
        public static string Search_Label_Find {
            get {
                return ResourceManager.GetString("Search_Label_Find", resourceCulture);
            }
        }
        
        public static string Search_QueryBox_Watermark {
            get {
                return ResourceManager.GetString("Search_QueryBox_Watermark", resourceCulture);
            }
        }
        
        public static string Search_Button_Find {
            get {
                return ResourceManager.GetString("Search_Button_Find", resourceCulture);
            }
        }
        
        public static string Search_RB_Text {
            get {
                return ResourceManager.GetString("Search_RB_Text", resourceCulture);
            }
        }
        
        public static string Search_RB_Style {
            get {
                return ResourceManager.GetString("Search_RB_Style", resourceCulture);
            }
        }
        
        public static string Search_RB_Actor {
            get {
                return ResourceManager.GetString("Search_RB_Actor", resourceCulture);
            }
        }
        
        public static string Search_RB_Effect {
            get {
                return ResourceManager.GetString("Search_RB_Effect", resourceCulture);
            }
        }
    }
}
