//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SelectAudio
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SelectAudio()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.Equals(null, resourceMan))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.SelectAudio", typeof(SelectAudio).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string SelectAudio_WindowTitle
        {
            get
            {
                return ResourceManager.GetString("SelectAudio_WindowTitle", resourceCulture);
            }
        }

        public static string SelectText
        {
            get
            {
                return ResourceManager.GetString("SelectText", resourceCulture);
            }
        }

        public static string SelectAudio_Button_Cancel
        {
            get
            {
                return ResourceManager.GetString("SelectAudio_Button_Cancel", resourceCulture);
            }
        }
        
        public static string SelectAudio_Button_Ok
        {
            get
            {
                return ResourceManager.GetString("SelectAudio_Button_Ok", resourceCulture);
            }
        }
    }
}
