//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShiftTimes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShiftTimes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ameko.I18N.ShiftTimes", typeof(ShiftTimes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ShiftTimes_Button_Ok {
            get {
                return ResourceManager.GetString("ShiftTimes_Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affect.
        /// </summary>
        public static string ShiftTimes_Header_Affect {
            get {
                return ResourceManager.GetString("ShiftTimes_Header_Affect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift By.
        /// </summary>
        public static string ShiftTimes_Header_ShiftBy {
            get {
                return ResourceManager.GetString("ShiftTimes_Header_ShiftBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        public static string ShiftTimes_Header_Times {
            get {
                return ResourceManager.GetString("ShiftTimes_Header_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rows.
        /// </summary>
        public static string ShiftTimes_RB_AllEvents {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_AllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward.
        /// </summary>
        public static string ShiftTimes_RB_Backward {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string ShiftTimes_RB_Both {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string ShiftTimes_RB_End {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string ShiftTimes_RB_Forward {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames.
        /// </summary>
        public static string ShiftTimes_RB_Frames {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Rows.
        /// </summary>
        public static string ShiftTimes_RB_SelectedEvents {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_SelectedEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ShiftTimes_RB_Start {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string ShiftTimes_RB_Time {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Times.
        /// </summary>
        public static string ShiftTimes_WindowTitle {
            get {
                return ResourceManager.GetString("ShiftTimes_WindowTitle", resourceCulture);
            }
        }
    }
}
