//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShiftTimes {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShiftTimes() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.ShiftTimes", typeof(ShiftTimes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ShiftTimes_WindowTitle {
            get {
                return ResourceManager.GetString("ShiftTimes_WindowTitle", resourceCulture);
            }
        }
        
        public static string ShiftTimes_Header_ShiftBy {
            get {
                return ResourceManager.GetString("ShiftTimes_Header_ShiftBy", resourceCulture);
            }
        }
        
        public static string ShiftTimes_RB_Time {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_Time", resourceCulture);
            }
        }
        
        public static string ShiftTimes_RB_Frames {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_Frames", resourceCulture);
            }
        }
        
        public static string ShiftTimes_RB_TowardEnd {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_TowardEnd", resourceCulture);
            }
        }
        
        public static string ShiftTimes_RB_TowardStart {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_TowardStart", resourceCulture);
            }
        }
        
        public static string ShiftTimes_Header_Affect {
            get {
                return ResourceManager.GetString("ShiftTimes_Header_Affect", resourceCulture);
            }
        }
        
        public static string ShiftTimes_RB_AllEvents {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_AllEvents", resourceCulture);
            }
        }
        
        public static string ShiftTimes_RB_SelectedEvents {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_SelectedEvents", resourceCulture);
            }
        }
        
        public static string ShiftTimes_Header_Times {
            get {
                return ResourceManager.GetString("ShiftTimes_Header_Times", resourceCulture);
            }
        }
        
        public static string ShiftTimes_RB_Both {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_Both", resourceCulture);
            }
        }
        
        public static string ShiftTimes_RB_Start {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_Start", resourceCulture);
            }
        }
        
        public static string ShiftTimes_RB_End {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_End", resourceCulture);
            }
        }
        
        public static string ShiftTimes_Button_Ok {
            get {
                return ResourceManager.GetString("ShiftTimes_Button_Ok", resourceCulture);
            }
        }
        
        public static string ShiftTimes_RB_Milliseconds {
            get {
                return ResourceManager.GetString("ShiftTimes_RB_Milliseconds", resourceCulture);
            }
        }
    }
}
