//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Spellcheck {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Spellcheck() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.Spellcheck", typeof(Spellcheck).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Spellcheck_WindowTitle {
            get {
                return ResourceManager.GetString("Spellcheck_WindowTitle", resourceCulture);
            }
        }
        
        public static string Spellcheck_Install_ProjectHeader {
            get {
                return ResourceManager.GetString("Spellcheck_Install_ProjectHeader", resourceCulture);
            }
        }
        
        public static string Spellcheck_Install_ConfigHeader {
            get {
                return ResourceManager.GetString("Spellcheck_Install_ConfigHeader", resourceCulture);
            }
        }
        
        public static string Spellcheck_Install_Capabilities {
            get {
                return ResourceManager.GetString("Spellcheck_Install_Capabilities", resourceCulture);
            }
        }
        
        public static string Spellcheck_Install_Notice {
            get {
                return ResourceManager.GetString("Spellcheck_Install_Notice", resourceCulture);
            }
        }
        
        public static string Spellcheck_Install_Button_Download {
            get {
                return ResourceManager.GetString("Spellcheck_Install_Button_Download", resourceCulture);
            }
        }
        
        public static string Spellcheck_Install_Button_Ignore {
            get {
                return ResourceManager.GetString("Spellcheck_Install_Button_Ignore", resourceCulture);
            }
        }
        
        public static string Spellcheck_Button_Change {
            get {
                return ResourceManager.GetString("Spellcheck_Button_Change", resourceCulture);
            }
        }
        
        public static string Spellcheck_Button_FindNext {
            get {
                return ResourceManager.GetString("Spellcheck_Button_FindNext", resourceCulture);
            }
        }
        
        public static string Spellcheck_Label_NotFound {
            get {
                return ResourceManager.GetString("Spellcheck_Label_NotFound", resourceCulture);
            }
        }
        
        public static string Spellcheck_Button_AddToProject {
            get {
                return ResourceManager.GetString("Spellcheck_Button_AddToProject", resourceCulture);
            }
        }
        
        public static string Spellcheck_Button_AddToGlobals {
            get {
                return ResourceManager.GetString("Spellcheck_Button_AddToGlobals", resourceCulture);
            }
        }
        
        public static string Spellcheck_Button_AddToBoth {
            get {
                return ResourceManager.GetString("Spellcheck_Button_AddToBoth", resourceCulture);
            }
        }
        
        public static string Spellcheck_Label_Dictionary {
            get {
                return ResourceManager.GetString("Spellcheck_Label_Dictionary", resourceCulture);
            }
        }
        
        public static string Spellcheck_Button_AddToProject_ToolTip {
            get {
                return ResourceManager.GetString("Spellcheck_Button_AddToProject_ToolTip", resourceCulture);
            }
        }
        
        public static string Spellcheck_Button_AddToGlobals_ToolTip {
            get {
                return ResourceManager.GetString("Spellcheck_Button_AddToGlobals_ToolTip", resourceCulture);
            }
        }
        
        public static string Spellcheck_Button_AddToBoth_ToolTip {
            get {
                return ResourceManager.GetString("Spellcheck_Button_AddToBoth_ToolTip", resourceCulture);
            }
        }
        
        public static string Spellcheck_Label_NoIssues {
            get {
                return ResourceManager.GetString("Spellcheck_Label_NoIssues", resourceCulture);
            }
        }
    }
}
