//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StyleEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StyleEditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ameko.I18N.StyleEditor", typeof(StyleEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string ColorDialog_Button_Select {
            get {
                return ResourceManager.GetString("ColorDialog_Button_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring.
        /// </summary>
        public static string ColorDialog_CheckBox_UseRing {
            get {
                return ResourceManager.GetString("ColorDialog_CheckBox_UseRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASS Color:.
        /// </summary>
        public static string ColorDialog_Label_AssColor {
            get {
                return ResourceManager.GetString("ColorDialog_Label_AssColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string ColorDialog_WindowTitle {
            get {
                return ResourceManager.GetString("ColorDialog_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align bottom-left (\an1).
        /// </summary>
        public static string StyleEditor_An1_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An1_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align bottom-center (\an2).
        /// </summary>
        public static string StyleEditor_An2_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An2_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align bottom-right (\an3).
        /// </summary>
        public static string StyleEditor_An3_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An3_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align middle-left (\an4).
        /// </summary>
        public static string StyleEditor_An4_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An4_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align center (\an5).
        /// </summary>
        public static string StyleEditor_An5_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An5_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align middle-right (\an6).
        /// </summary>
        public static string StyleEditor_An6_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An6_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align top-left (\an7).
        /// </summary>
        public static string StyleEditor_An7_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An7_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align top-center (\an8).
        /// </summary>
        public static string StyleEditor_An8_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An8_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align top-right (\an9).
        /// </summary>
        public static string StyleEditor_An9_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An9_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline &amp; Shadow.
        /// </summary>
        public static string StyleEditor_BBox1 {
            get {
                return ResourceManager.GetString("StyleEditor_BBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display an outline and shadow around each character.
        /// </summary>
        public static string StyleEditor_BBox1_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_BBox1_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box (Line).
        /// </summary>
        public static string StyleEditor_BBox3 {
            get {
                return ResourceManager.GetString("StyleEditor_BBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display an opaque box around each line.
        /// </summary>
        public static string StyleEditor_BBox3_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_BBox3_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box (Event).
        /// </summary>
        public static string StyleEditor_BBox4 {
            get {
                return ResourceManager.GetString("StyleEditor_BBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display an opaque box around all lines.
        /// </summary>
        public static string StyleEditor_BBox4_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_BBox4_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string StyleEditor_CheckBox_Bold {
            get {
                return ResourceManager.GetString("StyleEditor_CheckBox_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string StyleEditor_CheckBox_Italic {
            get {
                return ResourceManager.GetString("StyleEditor_CheckBox_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        public static string StyleEditor_CheckBox_Strikethrough {
            get {
                return ResourceManager.GetString("StyleEditor_CheckBox_Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string StyleEditor_CheckBox_Underline {
            get {
                return ResourceManager.GetString("StyleEditor_CheckBox_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family.
        /// </summary>
        public static string StyleEditor_FontFamilyBox_Watermark {
            get {
                return ResourceManager.GetString("StyleEditor_FontFamilyBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string StyleEditor_Header_Appearance {
            get {
                return ResourceManager.GetString("StyleEditor_Header_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration.
        /// </summary>
        public static string StyleEditor_Header_Decoration {
            get {
                return ResourceManager.GetString("StyleEditor_Header_Decoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positioning.
        /// </summary>
        public static string StyleEditor_Header_Positioning {
            get {
                return ResourceManager.GetString("StyleEditor_Header_Positioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name!.
        /// </summary>
        public static string StyleEditor_InvalidName {
            get {
                return ResourceManager.GetString("StyleEditor_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string StyleEditor_Label_Alignment {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline.
        /// </summary>
        public static string StyleEditor_Label_BorderThickness {
            get {
                return ResourceManager.GetString("StyleEditor_Label_BorderThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string StyleEditor_Label_MarginLeft {
            get {
                return ResourceManager.GetString("StyleEditor_Label_MarginLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string StyleEditor_Label_MarginRight {
            get {
                return ResourceManager.GetString("StyleEditor_Label_MarginRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margins.
        /// </summary>
        public static string StyleEditor_Label_Margins {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Margins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string StyleEditor_Label_MarginVertical {
            get {
                return ResourceManager.GetString("StyleEditor_Label_MarginVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline.
        /// </summary>
        public static string StyleEditor_Label_Outline {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string StyleEditor_Label_Primary {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation (deg).
        /// </summary>
        public static string StyleEditor_Label_Rotation {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Scale %.
        /// </summary>
        public static string StyleEditor_Label_ScaleX {
            get {
                return ResourceManager.GetString("StyleEditor_Label_ScaleX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Scale %.
        /// </summary>
        public static string StyleEditor_Label_ScaleY {
            get {
                return ResourceManager.GetString("StyleEditor_Label_ScaleY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        public static string StyleEditor_Label_Secondary {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow.
        /// </summary>
        public static string StyleEditor_Label_Shadow {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Shadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow.
        /// </summary>
        public static string StyleEditor_Label_ShadowDistance {
            get {
                return ResourceManager.GetString("StyleEditor_Label_ShadowDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing.
        /// </summary>
        public static string StyleEditor_Label_Spacing {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left margin.
        /// </summary>
        public static string StyleEditor_MarginLeft_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_MarginLeft_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right margin.
        /// </summary>
        public static string StyleEditor_MarginRight_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_MarginRight_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical margin.
        /// </summary>
        public static string StyleEditor_MarginVertical_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_MarginVertical_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Name.
        /// </summary>
        public static string StyleEditor_NameBox_Watermark {
            get {
                return ResourceManager.GetString("StyleEditor_NameBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Info.
        /// </summary>
        public static string StyleEditor_Section_BasicInfo {
            get {
                return ResourceManager.GetString("StyleEditor_Section_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string StyleEditor_Section_Colors {
            get {
                return ResourceManager.GetString("StyleEditor_Section_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string StyleEditor_Section_Font {
            get {
                return ResourceManager.GetString("StyleEditor_Section_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Editor.
        /// </summary>
        public static string StyleEditor_WindowTitle {
            get {
                return ResourceManager.GetString("StyleEditor_WindowTitle", resourceCulture);
            }
        }
    }
}
