//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StyleEditor {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StyleEditor() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.StyleEditor", typeof(StyleEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string StyleEditor_WindowTitle {
            get {
                return ResourceManager.GetString("StyleEditor_WindowTitle", resourceCulture);
            }
        }
        
        public static string StyleEditor_Section_BasicInfo {
            get {
                return ResourceManager.GetString("StyleEditor_Section_BasicInfo", resourceCulture);
            }
        }
        
        public static string StyleEditor_InvalidName {
            get {
                return ResourceManager.GetString("StyleEditor_InvalidName", resourceCulture);
            }
        }
        
        public static string StyleEditor_NameBox_Watermark {
            get {
                return ResourceManager.GetString("StyleEditor_NameBox_Watermark", resourceCulture);
            }
        }
        
        public static string StyleEditor_Section_Font {
            get {
                return ResourceManager.GetString("StyleEditor_Section_Font", resourceCulture);
            }
        }
        
        public static string StyleEditor_FontFamilyBox_Watermark {
            get {
                return ResourceManager.GetString("StyleEditor_FontFamilyBox_Watermark", resourceCulture);
            }
        }
        
        public static string StyleEditor_CheckBox_Bold {
            get {
                return ResourceManager.GetString("StyleEditor_CheckBox_Bold", resourceCulture);
            }
        }
        
        public static string StyleEditor_CheckBox_Italic {
            get {
                return ResourceManager.GetString("StyleEditor_CheckBox_Italic", resourceCulture);
            }
        }
        
        public static string StyleEditor_CheckBox_Underline {
            get {
                return ResourceManager.GetString("StyleEditor_CheckBox_Underline", resourceCulture);
            }
        }
        
        public static string StyleEditor_CheckBox_Strikethrough {
            get {
                return ResourceManager.GetString("StyleEditor_CheckBox_Strikethrough", resourceCulture);
            }
        }
        
        public static string StyleEditor_Section_Colors {
            get {
                return ResourceManager.GetString("StyleEditor_Section_Colors", resourceCulture);
            }
        }
        
        public static string StyleEditor_Label_Primary {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Primary", resourceCulture);
            }
        }
        
        public static string StyleEditor_Label_Secondary {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Secondary", resourceCulture);
            }
        }
        
        public static string StyleEditor_Label_Outline {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Outline", resourceCulture);
            }
        }
        
        public static string StyleEditor_Label_Shadow {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Shadow", resourceCulture);
            }
        }
        
        public static string StyleEditor_Header_Positioning {
            get {
                return ResourceManager.GetString("StyleEditor_Header_Positioning", resourceCulture);
            }
        }
        
        public static string StyleEditor_Label_Margins {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Margins", resourceCulture);
            }
        }
        
        public static string StyleEditor_Label_Alignment {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Alignment", resourceCulture);
            }
        }
        
        public static string StyleEditor_MarginLeft_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_MarginLeft_ToolTip", resourceCulture);
            }
        }
        
        public static string StyleEditor_MarginRight_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_MarginRight_ToolTip", resourceCulture);
            }
        }
        
        public static string StyleEditor_MarginVertical_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_MarginVertical_ToolTip", resourceCulture);
            }
        }
        
        public static string StyleEditor_An1_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An1_ToolTip", resourceCulture);
            }
        }
        
        public static string StyleEditor_An2_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An2_ToolTip", resourceCulture);
            }
        }
        
        public static string StyleEditor_An3_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An3_ToolTip", resourceCulture);
            }
        }
        
        public static string StyleEditor_An4_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An4_ToolTip", resourceCulture);
            }
        }
        
        public static string StyleEditor_An5_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An5_ToolTip", resourceCulture);
            }
        }
        
        public static string StyleEditor_An6_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An6_ToolTip", resourceCulture);
            }
        }
        
        public static string StyleEditor_An7_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An7_ToolTip", resourceCulture);
            }
        }
        
        public static string StyleEditor_An8_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An8_ToolTip", resourceCulture);
            }
        }
        
        public static string StyleEditor_An9_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_An9_ToolTip", resourceCulture);
            }
        }
        
        public static string StyleEditor_Label_MarginLeft {
            get {
                return ResourceManager.GetString("StyleEditor_Label_MarginLeft", resourceCulture);
            }
        }
        
        public static string StyleEditor_Label_MarginRight {
            get {
                return ResourceManager.GetString("StyleEditor_Label_MarginRight", resourceCulture);
            }
        }
        
        public static string StyleEditor_Label_MarginVertical {
            get {
                return ResourceManager.GetString("StyleEditor_Label_MarginVertical", resourceCulture);
            }
        }
        
        public static string StyleEditor_Header_Decoration {
            get {
                return ResourceManager.GetString("StyleEditor_Header_Decoration", resourceCulture);
            }
        }
        
        public static string StyleEditor_Label_BorderThickness {
            get {
                return ResourceManager.GetString("StyleEditor_Label_BorderThickness", resourceCulture);
            }
        }
        
        public static string StyleEditor_Label_ShadowDistance {
            get {
                return ResourceManager.GetString("StyleEditor_Label_ShadowDistance", resourceCulture);
            }
        }
        
        public static string StyleEditor_BBox4 {
            get {
                return ResourceManager.GetString("StyleEditor_BBox4", resourceCulture);
            }
        }
        
        public static string StyleEditor_BBox1 {
            get {
                return ResourceManager.GetString("StyleEditor_BBox1", resourceCulture);
            }
        }
        
        public static string StyleEditor_BBox3 {
            get {
                return ResourceManager.GetString("StyleEditor_BBox3", resourceCulture);
            }
        }
        
        public static string StyleEditor_BBox1_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_BBox1_ToolTip", resourceCulture);
            }
        }
        
        public static string StyleEditor_BBox3_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_BBox3_ToolTip", resourceCulture);
            }
        }
        
        public static string StyleEditor_BBox4_ToolTip {
            get {
                return ResourceManager.GetString("StyleEditor_BBox4_ToolTip", resourceCulture);
            }
        }
        
        public static string StyleEditor_Header_Appearance {
            get {
                return ResourceManager.GetString("StyleEditor_Header_Appearance", resourceCulture);
            }
        }
        
        public static string StyleEditor_Label_ScaleX {
            get {
                return ResourceManager.GetString("StyleEditor_Label_ScaleX", resourceCulture);
            }
        }
        
        public static string StyleEditor_Label_ScaleY {
            get {
                return ResourceManager.GetString("StyleEditor_Label_ScaleY", resourceCulture);
            }
        }
        
        public static string StyleEditor_Label_Rotation {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Rotation", resourceCulture);
            }
        }
        
        public static string StyleEditor_Label_Spacing {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Spacing", resourceCulture);
            }
        }
        
        public static string ColorDialog_WindowTitle {
            get {
                return ResourceManager.GetString("ColorDialog_WindowTitle", resourceCulture);
            }
        }
        
        public static string ColorDialog_CheckBox_UseRing {
            get {
                return ResourceManager.GetString("ColorDialog_CheckBox_UseRing", resourceCulture);
            }
        }
        
        public static string ColorDialog_Label_AssColor {
            get {
                return ResourceManager.GetString("ColorDialog_Label_AssColor", resourceCulture);
            }
        }
        
        public static string ColorDialog_Button_Select {
            get {
                return ResourceManager.GetString("ColorDialog_Button_Select", resourceCulture);
            }
        }
        
        public static string StyleEditor_Button_Save {
            get {
                return ResourceManager.GetString("StyleEditor_Button_Save", resourceCulture);
            }
        }
    }
}
