//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StylesManager {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StylesManager() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.StylesManager", typeof(StylesManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string StylesManager_Title {
            get {
                return ResourceManager.GetString("StylesManager_Title", resourceCulture);
            }
        }
        
        public static string StylesManager_GlobalStyles {
            get {
                return ResourceManager.GetString("StylesManager_GlobalStyles", resourceCulture);
            }
        }
        
        public static string StylesManager_ProjectStyles {
            get {
                return ResourceManager.GetString("StylesManager_ProjectStyles", resourceCulture);
            }
        }
        
        public static string StylesManager_DocumentStyles {
            get {
                return ResourceManager.GetString("StylesManager_DocumentStyles", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_Delete {
            get {
                return ResourceManager.GetString("StylesManager_Button_Delete", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_Duplicate {
            get {
                return ResourceManager.GetString("StylesManager_Button_Duplicate", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_Edit {
            get {
                return ResourceManager.GetString("StylesManager_Button_Edit", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_New {
            get {
                return ResourceManager.GetString("StylesManager_Button_New", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_CopyToProject {
            get {
                return ResourceManager.GetString("StylesManager_Button_CopyToProject", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_CopyToGlobal {
            get {
                return ResourceManager.GetString("StylesManager_Button_CopyToGlobal", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_CopyToDocument {
            get {
                return ResourceManager.GetString("StylesManager_Button_CopyToDocument", resourceCulture);
            }
        }
        
        public static string StylesManager_CopyAppendage {
            get {
                return ResourceManager.GetString("StylesManager_CopyAppendage", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_Duplicate_ToolTip {
            get {
                return ResourceManager.GetString("StylesManager_Button_Duplicate_ToolTip", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_Delete_ToolTip {
            get {
                return ResourceManager.GetString("StylesManager_Button_Delete_ToolTip", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_Edit_ToolTip {
            get {
                return ResourceManager.GetString("StylesManager_Button_Edit_ToolTip", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_New_ToolTip {
            get {
                return ResourceManager.GetString("StylesManager_Button_New_ToolTip", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_CopyToDocument_ToolTip {
            get {
                return ResourceManager.GetString("StylesManager_Button_CopyToDocument_ToolTip", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_CopyToGlobal_ToolTip {
            get {
                return ResourceManager.GetString("StylesManager_Button_CopyToGlobal_ToolTip", resourceCulture);
            }
        }
        
        public static string StylesManager_Button_CopyToProject_ToolTip {
            get {
                return ResourceManager.GetString("StylesManager_Button_CopyToProject_ToolTip", resourceCulture);
            }
        }
    }
}
