//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StyleEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StyleEditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ameko.I18N.StyleEditor", typeof(StyleEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string StyleEditor_CheckBox_Bold {
            get {
                return ResourceManager.GetString("StyleEditor_CheckBox_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string StyleEditor_CheckBox_Italic {
            get {
                return ResourceManager.GetString("StyleEditor_CheckBox_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        public static string StyleEditor_CheckBox_Strikethrough {
            get {
                return ResourceManager.GetString("StyleEditor_CheckBox_Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string StyleEditor_CheckBox_Underline {
            get {
                return ResourceManager.GetString("StyleEditor_CheckBox_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family.
        /// </summary>
        public static string StyleEditor_FontFamilyBox_Watermark {
            get {
                return ResourceManager.GetString("StyleEditor_FontFamilyBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name!.
        /// </summary>
        public static string StyleEditor_InvalidName {
            get {
                return ResourceManager.GetString("StyleEditor_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline.
        /// </summary>
        public static string StyleEditor_Label_Outline {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string StyleEditor_Label_Primary {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        public static string StyleEditor_Label_Secondary {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow.
        /// </summary>
        public static string StyleEditor_Label_Shadow {
            get {
                return ResourceManager.GetString("StyleEditor_Label_Shadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Name.
        /// </summary>
        public static string StyleEditor_NameBox_Watermark {
            get {
                return ResourceManager.GetString("StyleEditor_NameBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Info.
        /// </summary>
        public static string StyleEditor_Section_BasicInfo {
            get {
                return ResourceManager.GetString("StyleEditor_Section_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string StyleEditor_Section_Colors {
            get {
                return ResourceManager.GetString("StyleEditor_Section_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string StyleEditor_Section_Font {
            get {
                return ResourceManager.GetString("StyleEditor_Section_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Editor.
        /// </summary>
        public static string StyleEditor_WindowTitle {
            get {
                return ResourceManager.GetString("StyleEditor_WindowTitle", resourceCulture);
            }
        }
    }
}
