//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StylesManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StylesManager() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ameko.I18N.StylesManager", typeof(StylesManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string StylesManager_Button_Copy {
            get {
                return ResourceManager.GetString("StylesManager_Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Document.
        /// </summary>
        public static string StylesManager_Button_CopyToDocument {
            get {
                return ResourceManager.GetString("StylesManager_Button_CopyToDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Global.
        /// </summary>
        public static string StylesManager_Button_CopyToGlobal {
            get {
                return ResourceManager.GetString("StylesManager_Button_CopyToGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Solution.
        /// </summary>
        public static string StylesManager_Button_CopyToSolution {
            get {
                return ResourceManager.GetString("StylesManager_Button_CopyToSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string StylesManager_Button_Delete {
            get {
                return ResourceManager.GetString("StylesManager_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string StylesManager_Button_Edit {
            get {
                return ResourceManager.GetString("StylesManager_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string StylesManager_Button_New {
            get {
                return ResourceManager.GetString("StylesManager_Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string StylesManager_CopyAppendage {
            get {
                return ResourceManager.GetString("StylesManager_CopyAppendage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Styles.
        /// </summary>
        public static string StylesManager_DocumentStyles {
            get {
                return ResourceManager.GetString("StylesManager_DocumentStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Styles.
        /// </summary>
        public static string StylesManager_GlobalStyles {
            get {
                return ResourceManager.GetString("StylesManager_GlobalStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Styles.
        /// </summary>
        public static string StylesManager_SolutionStyles {
            get {
                return ResourceManager.GetString("StylesManager_SolutionStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles Manager.
        /// </summary>
        public static string StylesManager_Title {
            get {
                return ResourceManager.GetString("StylesManager_Title", resourceCulture);
            }
        }
    }
}
