// SPDX-License-Identifier: MPL-2.0

using System.IO.Abstractions.TestingHelpers;
using AssCS.IO;
using static TestingUtils.TestableUri;

namespace AssCS.Tests;

public class AssParserTests
{
    [Test]
    public async Task Parse()
    {
        var fs = new MockFileSystem();
        var path = MakeTestableUri(fs, "test.ass");
        fs.AddFile(path.LocalPath, new MockFileData(File1));

        var ap = new AssParser();

        var doc = ap.Parse(fs, path);

        await Assert.That(doc).IsNotNull();
        await Assert.That(doc.Version).IsEqualTo(AssVersion.V400P);

        await Assert.That(doc.ScriptInfoManager.Get("Title")).IsEqualTo("English (US)");

        await Assert
            .That(doc.GarbageManager.GetString("Video File"))
            .IsEqualTo("spicewolf_web_14.mkv");
        await Assert.That(doc.StyleManager.Styles.Count).IsEqualTo(2);
        await Assert.That(doc.EventManager.Count).IsEqualTo(7);
        await Assert.That(doc.ExtradataManager.Get().Count).IsEqualTo(0); // Because it's inline-encoded and therefore ignored

        await Assert
            .That(doc.EventManager.Head.Text)
            .IsEqualTo("Is aught the matter?{Begin Volume 3}");
        await Assert.That(doc.EventManager.Head.Actor).IsEqualTo("Holo");

        await Assert.That(doc.StyleManager.Get("Default").FontFamily).IsEqualTo("Volkhov");
    }

    // This file has been modified for brevity
    private const string File1 = """
        [Script Info]
        ; Script generated by Aegisub 9706-cibuilds-20caaabc0
        ; http://www.aegisub.org/
        Title: English (US)
        ScriptType: v4.00+
        PlayResX: 1920
        PlayResY: 1080
        WrapStyle: 0
        ScaledBorderAndShadow: yes
        YCbCr Matrix: TV.709

        [Aegisub Project Garbage]
        Last Style Storage: Spice & Wolf
        Audio File: spicewolf_web_14.mkv
        Video File: spicewolf_web_14.mkv

        [V4+ Styles]
        Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
        Style: Default,Volkhov,69,&H00FFFFFF,&H000000FF,&H00052030,&HA0052030,-1,0,0,0,100,105,0,0,1,4.75,2.1,2,275,275,60,1
        Style: Italics,Volkhov,69,&H00FFFFFF,&H000000FF,&H00052030,&HA0052030,-1,-1,0,0,100,105,0,0,1,4.75,2.1,2,275,275,60,1

        [Events]
        Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
        Dialogue: 0,0:00:16.41,0:00:17.40,Default,Holo,0,0,0,,Is aught the matter?{Begin Volume 3}
        Dialogue: 0,0:00:17.40,0:00:19.37,Default,Lawrence,0,0,0,,Hurry up and get your tail under the tarp.
        Dialogue: 0,0:00:19.37,0:00:22.37,Default,Holo,0,0,0,,My tail is not your personal quilt!
        Dialogue: 0,0:00:22.37,0:00:29.43,Default,Lawrence,0,0,0,,{\q2}It's such fine fur, though; putting it under the tarp\Nkeeps my legs as warm as a mountain of pelts would.
        Dialogue: 0,0:00:36.93,0:00:38.89,Default,Lawrence,0,0,0,,That's right! I have a gift for you!
        Dialogue: 0,0:00:44.23,0:00:47.71,Default,Lawrence,0,0,0,,We were able to get by until now\Nas long as you dressed as a nun,
        Dialogue: 0,0:00:47.71,0:00:49.57,Default,Lawrence,0,0,0,,but it'll be different in Kumersun.

        [Aegisub Extradata]
        Data: 5,a-mo,e{"uuid"#3A"48541a34-fcab-429a-86f6-cb3805322a9f"#2C"originalText"#3A"{\\fscx123\\fscy115\\fnPapyrus\\fs210\\\\fsp2\\b1\\blur0.7\\\\\\c&HFAFAFB&\\t(0#2C768#2C1#2C\\c&H1F1F1F&)\\t(7149#2C0#2C1#2C\\alpha&HFF&)\\pos(960#2C360)}Spice \\hand\\h Wolf"}
        """;
}
