// SPDX-License-Identifier: MPL-2.0

namespace AssCS.Tests;

public class EventTests
{
    private const string BasicEvent =
        "Dialogue: 0,0:02:10.57,0:02:13.51,Default,Heiter,0,0,0,,It's the victorious return of the heroes' party.";
    private const string TagEvent =
        @"Dialogue: 0,0:11:34.65,0:11:37.38,Default,Frieren,0,0,0,,You're {\i1}bald{\i0}, there's no point in fussing.";

    /// <summary>
    /// Example of an event generated by Closed Caption Converter. Note the empty or decimal margin values
    /// </summary>
    private const string CcsEvent =
        @"Dialogue: 0,0:03:09.48,0:03:12.40,TopCenter,,,,25.00,,WE CAN JUST CALL THIS THE END OF THE GAME, YEAH?\N- It was a big hit.";

    [Test]
    public async Task FromAss()
    {
        var e = Event.FromAss(1, BasicEvent);

        await Assert.That(e).IsNotNull();
        await Assert.That(e.IsComment).IsFalse();
        await Assert.That(e.Layer).IsEqualTo(0);
        await Assert.That(e.Start).IsEqualTo(Time.FromMillis(130570)); // 2:10.57
        await Assert.That(e.End).IsEqualTo(Time.FromMillis(133510)); // 2:13.51
        await Assert.That(e.Style).IsEqualTo("Default");
        await Assert.That(e.Actor).IsEqualTo("Heiter");
        await Assert.That(e.Margins).IsEqualTo(new Margins(0, 0, 0));
        await Assert.That(e.Effect).IsEqualTo(string.Empty);
        await Assert.That(e.Text).IsEqualTo("It's the victorious return of the heroes' party.");
    }

    [Test]
    public async Task FromAss_Ccs()
    {
        var e = Event.FromAss(1, CcsEvent);

        await Assert.That(e).IsNotNull();
        await Assert.That(e.Margins).IsEqualTo(new Margins(0, 0, 25));
    }

    [Test]
    public async Task FromAss_Malformed_ReturnsNull()
    {
        var e = Event.FromAss(1, "This portion of today's video is sponsored by Overstock.com");

        await Assert.That(e).IsNull();
    }

    [Test]
    public async Task AsAss()
    {
        var e = Event.FromAss(1, BasicEvent);

        await Assert.That(e).IsNotNull();
        await Assert.That(e.AsAss()).IsEqualTo(BasicEvent);
    }

    [Test]
    public async Task StripText()
    {
        var e = Event.FromAss(1, TagEvent)!;
        e.StripTags();

        await Assert.That(e.Text).IsEqualTo("You're bald, there's no point in fussing.");
    }

    [Test]
    public async Task Clone()
    {
        var e1 = Event.FromAss(1, BasicEvent)!;
        var e2 = e1.Clone();

        await Assert.That(e2).IsEqualTo(e1);
    }

    [Test]
    public async Task CollidesWith()
    {
        var e1 = new Event(1) { Start = Time.FromSeconds(0), End = Time.FromSeconds(5) };
        var e2 = new Event(2) { Start = Time.FromSeconds(2.5), End = Time.FromSeconds(7.5) };
        var e3 = new Event(3) { Start = Time.FromSeconds(10), End = Time.FromSeconds(15) };

        await Assert.That(e1.CollidesWith(e2)).IsTrue();
        await Assert.That(e2.CollidesWith(e1)).IsTrue();

        await Assert.That(e1.CollidesWith(e3)).IsFalse();
        await Assert.That(e2.CollidesWith(e3)).IsFalse();
    }

    [Test]
    public async Task TransformCodeToAss()
    {
        var evt = new Event(1) { Text = "Line1\n  Line2" };
        await Assert.That(evt.TransformCodeToAss()).Contains("--[[2]]");
    }

    [Test]
    public async Task TransformAssToCode()
    {
        var evt = new Event(1) { Text = "Line1--[[2]]Line2" };
        await Assert.That(evt.TransformAssToCode()).Contains(Environment.NewLine + "  Line2");
    }

    [Test]
    public async Task SetFields_NoFlags()
    {
        var baseline = Event.FromAss(1, BasicEvent)!;
        var evt1 = Event.FromAss(1, BasicEvent)!;
        var evt2 = Event.FromAss(2, TagEvent)!;
        const EventField fields = EventField.None;

        evt1.SetFields(fields, evt2);

        await Assert.That(evt1.IsCongruentWith(baseline)).IsTrue();
    }

    [Test]
    public async Task SetFields_AllFlags()
    {
        var baseline = Event.FromAss(1, BasicEvent)!;
        var evt1 = Event.FromAss(1, BasicEvent)!;
        var evt2 = Event.FromAss(2, TagEvent)!;
        const EventField fields =
            EventField.Comment
            | EventField.Layer
            | EventField.StartTime
            | EventField.EndTime
            | EventField.Style
            | EventField.Actor
            | EventField.MarginLeft
            | EventField.MarginRight
            | EventField.MarginVertical
            | EventField.Effect
            | EventField.Text;

        evt1.SetFields(fields, evt2);

        await Assert.That(evt1.IsCongruentWith(baseline)).IsFalse();
        await Assert.That(evt1.IsCongruentWith(evt2)).IsTrue();
    }

    #region Cps & Line Width

    [Test]
    public async Task Cps_NoTags()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text = "The quick brown fox jumps over the lazy dog",
        };

        await Assert.That(e.Cps).IsEqualTo(35);
    }

    [Test]
    public async Task Cps_Newline()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text = "The quick brown fox\\Njumps over the lazy dog",
        };

        await Assert.That(e.Cps).IsEqualTo(35);
    }

    [Test]
    public async Task Cps_Random_Backslash()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text = @"The quick brown fox\Njumps \over the lazy dog",
        };

        await Assert.That(e.Cps).IsEqualTo(35);
    }

    [Test]
    public async Task Cps_Floating_Newline()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text = "The quick brown fox \\N jumps over the lazy dog",
        };

        await Assert.That(e.Cps).IsEqualTo(35);
    }

    [Test]
    public async Task Cps_Hard_Space()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text = "The quick brown fox\\hjumps over the lazy dog",
        };

        await Assert.That(e.Cps).IsEqualTo(35);
    }

    [Test]
    public async Task Cps_Terminating_Newline()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text = "The quick brown fox jumps over the lazy dog\\N",
        };

        await Assert.That(e.Cps).IsEqualTo(35);
    }

    [Test]
    public async Task Cps_Tags()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text =
                @"The quick {\i1}brown{\i0} fox{it could be an artic fox} jumps over the lazy dog",
        };

        await Assert.That(e.Cps).IsEqualTo(35);
    }

    [Test]
    public async Task Cps_Kanji()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text = "この番組は、ご覧のスポンサーの提供でお送りします。",
        };

        await Assert.That(e.Cps).IsEqualTo(23);
    }

    [Test]
    public async Task Cps_Decomposed_Hangul()
    {
        var e1 = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text = "\u1100\u1161\u11a8", // 각
        };

        var e2 = new Event(2)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text = "\uac01", // 각
        };

        await Assert.That(e1.Cps).IsEqualTo(e2.Cps);
    }

    [Test]
    public async Task Cps_Ffi_Ligature()
    {
        var e1 = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text = "ﬃ",
        };

        var e2 = new Event(2)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text = "ffi",
        };

        await Assert.That(e1.Cps).IsNotEqualTo(e2.Cps);
    }

    [Test]
    public async Task Cps_Multilingual()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text =
                "He said, \"Hello world!\"\\N彼は「おはよう世界！」と言いました。\\nОн сказал: «Здравствуй, мир!»",
        };

        await Assert.That(e.Cps).IsEqualTo(51);
    }

    [Test]
    public async Task MaxLineWidth_SingleLine()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text = "The quick brown fox jumps over the lazy dog",
        };

        await Assert.That(e.MaxLineWidth).IsEqualTo(35);
    }

    [Test]
    public async Task MaxLineWidth_SingleLine_Tags()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text =
                @"The quick {\i1}brown{\i0} fox{it could be an artic fox} jumps over the lazy dog",
        };

        await Assert.That(e.MaxLineWidth).IsEqualTo(35);
    }

    [Test]
    public async Task MaxLineWidth_MultipleLines()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text = "The quick brown fox\\Njumps over the lazy dog",
        };

        await Assert.That(e.MaxLineWidth).IsEqualTo(19);
    }

    [Test]
    public async Task MaxLineWidth_MultipeLines_Tags()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text =
                @"The quick {\i1}brown{\i0} fox{it could be an artic fox}\Njumps over the lazy dog",
        };

        await Assert.That(e.MaxLineWidth).IsEqualTo(19);
    }

    [Test]
    public async Task MaxLineWidth_Kanji()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text = "この番組は、\\nご覧のスポンサーの提供でお送りします。",
        };

        await Assert.That(e.MaxLineWidth).IsEqualTo(19);
    }

    [Test]
    public async Task MaxLineWidth_Decomposed_Hangul()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text = "\u1100\u1161\u11a8\\N\uac01", // 각 \n 각
        };

        await Assert.That(e.MaxLineWidth).IsEqualTo(1);
    }

    [Test]
    public async Task MaxLineWidth_Ffi_Ligature()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text = "ﬃ\\Nffi",
        };

        await Assert.That(e.MaxLineWidth).IsEqualTo(3);
    }

    [Test]
    public async Task MaxLineWidth_Multilingual()
    {
        var e = new Event(1)
        {
            Start = Time.FromSeconds(0),
            End = Time.FromSeconds(1),
            Text =
                "He said, \"Hello world!\"\\N彼は「おはよう世界！」と言いました。\\nОн сказал: «Здравствуй, мир!»",
        };

        await Assert.That(e.MaxLineWidth).IsEqualTo(26);
    }

    #endregion Cps & Line Width

    #region GetStrippedText

    [Test]
    public async Task GetStrippedText_Normal()
    {
        var e = Event.FromAss(1, TagEvent);

        await Assert.That(e).IsNotNull();
        await Assert
            .That(e.GetStrippedText())
            .IsEqualTo("You're bald, there's no point in fussing.");
    }

    [Test]
    public async Task GetStrippedText_Empty()
    {
        var e = new Event(1);

        await Assert.That(e.GetStrippedText()).IsEqualTo(string.Empty);
    }

    [Test]
    public async Task GetStrippedText_OnlyTag()
    {
        var e = new Event(1) { Text = "{\\q2}" };

        await Assert.That(e.GetStrippedText()).IsEqualTo(string.Empty);
    }

    [Test]
    public async Task GetStrippedText_Short_After()
    {
        var e = new Event(1) { Text = "{\\q2}A" };

        await Assert.That(e.GetStrippedText()).IsEqualTo("A");
    }

    [Test]
    public async Task GetStrippedText_Short_Before()
    {
        var e = new Event(1) { Text = "A{\\q2}" };

        await Assert.That(e.GetStrippedText()).IsEqualTo("A");
    }

    [Test]
    public async Task GetStrippedText_RandomBraces()
    {
        var e = new Event(1) { Text = "a{b}c}d{{e" };

        await Assert.That(e.GetStrippedText()).IsEqualTo("ac}d{{e");
    }

    [Test]
    public async Task GetStrippedText_OpeningBrace()
    {
        var e = new Event(1) { Text = "a{b}cd{e" };

        await Assert.That(e.GetStrippedText()).IsEqualTo("acd{e");
    }

    [Test]
    public async Task GetStrippedText_ExtraOpeningBrace()
    {
        var e = new Event(1) { Text = "a{{b}cde" };

        await Assert.That(e.GetStrippedText()).IsEqualTo("acde");
    }

    [Test]
    public async Task GetStrippedText_TrailingOpeningBrace()
    {
        var e = new Event(1) { Text = "a{b}cde{" };

        await Assert.That(e.GetStrippedText()).IsEqualTo("acde{");
    }

    [Test]
    public async Task GetStrippedText_ClosingBrace()
    {
        var e = new Event(1) { Text = "a{b}cd}e" };

        await Assert.That(e.GetStrippedText()).IsEqualTo("acd}e");
    }

    [Test]
    public async Task GetStrippedText_ExtraClosingBrace()
    {
        var e = new Event(1) { Text = "a{b}}cde" };

        await Assert.That(e.GetStrippedText()).IsEqualTo("a}cde");
    }

    [Test]
    public async Task GetStrippedText_TrailingClosingBrace()
    {
        var e = new Event(1) { Text = "a{b}cde}" };

        await Assert.That(e.GetStrippedText()).IsEqualTo("acde}");
    }

    #endregion GetStrippedText

    #region ToggleTag

    [Test]
    public async Task ToggleTag_ToggleTagPair()
    {
        var e = Event.FromAss(1, TagEvent)!;
        var s = new Style(1); // Default style

        e.ToggleTag("i", s, 12, 16); // Inside the tag

        await Assert.That(e.Text).IsEqualTo(@"You're {\i0}bald{\i1}, there's no point in fussing.");
    }

    [Test]
    public async Task ToggleTag_AddToExistingPair()
    {
        var e = Event.FromAss(1, TagEvent)!;
        var s = new Style(1); // Default style

        e.ToggleTag("b", s, 12, 16); // Inside the tag

        await Assert
            .That(e.Text)
            .IsEqualTo(@"You're {\i1\b1}bald{\i0\b0}, there's no point in fussing.");
    }

    [Test]
    public async Task ToggleTag_AddTag()
    {
        var e = Event.FromAss(1, BasicEvent)!;
        var s = new Style(1); // Default style

        e.ToggleTag("i", s, 0, 0);

        await Assert
            .That(e.Text)
            .IsEqualTo(@"{\i1}It's the victorious return of the heroes' party.");
    }

    #endregion ToggleTag

    #region Diff

    [Test]
    public async Task Diff_Identical()
    {
        var evt1 = Event.FromAss(1, BasicEvent);
        var evt2 = Event.FromAss(2, BasicEvent);

        var result = evt1.Diff(evt2);

        await Assert.That(result).IsEqualTo(EventField.None);
    }

    [Test]
    public async Task Diff_OneChange()
    {
        var evt1 = Event.FromAss(1, BasicEvent);
        var evt2 = Event.FromAss(2, BasicEvent);
        evt2.Text = "Seven apples on a witch's tree, with seven seeds to plant inside of me";

        var result = evt1.Diff(evt2);

        await Assert.That(result).IsEqualTo(EventField.Text);
    }

    [Test]
    public async Task Diff_MultipleChanges()
    {
        var evt1 = Event.FromAss(1, BasicEvent);
        var evt2 = Event.FromAss(2, BasicEvent);
        evt2.Text = "Seven apples on a witch's tree, with seven seeds to plant inside of me";
        evt2.Actor = "Lawrence";

        var result = evt1.Diff(evt2);

        await Assert.That(result).IsEqualTo(EventField.Text | EventField.Actor);
    }

    #endregion Diff
}
