// SPDX-License-Identifier: MPL-2.0

namespace AssCS.Tests;

public class StyleTests
{
    private const string BasicStyle =
        "Style: Default,Noto Serif,69,&H00FFFFFF,&H00000000,&H0012291F,&HA012291F,-1,0,0,0,100,100,0,0,1,4.4,2.2,2,275,275,60,1";

    /// <summary>
    /// Example of a style generated by Closed Caption Converter. Note the illegal spaces and decimals
    /// </summary>
    private const string CcsStyle =
        "Style: Default, Arial, 24,&H00B4FCFC,&H00B4FCFC,&H00000008,&H80000008,0,0,0,0,100,100,0.00,0.00,1,1.00,2.00,2,25.00,25.00,25.00,0";

    [Test]
    public async Task FromAss()
    {
        var s = Style.FromAss(1, BasicStyle);

        await Assert.That(s).IsNotNull();
        await Assert.That(s.Name).IsEqualTo("Default");
        await Assert.That(s.FontFamily).IsEqualTo("Noto Serif");
        await Assert.That(s.FontSize).IsEqualTo(69);
        await Assert.That(s.PrimaryColor).IsEqualTo(Color.FromRgb(0xFF, 0xFF, 0xFF));
        await Assert.That(s.SecondaryColor).IsEqualTo(Color.FromRgb(0x0, 0x0, 0x0));
        await Assert.That(s.OutlineColor).IsEqualTo(Color.FromRgb(0x1F, 0x29, 0x12));
        await Assert.That(s.ShadowColor).IsEqualTo(Color.FromRgba(0x1F, 0x29, 0x12, 0xA0));
        await Assert.That(s.IsBold).IsTrue();
        await Assert.That(s.IsItalic).IsFalse();
        await Assert.That(s.IsUnderline).IsFalse();
        await Assert.That(s.IsStrikethrough).IsFalse();
        await Assert.That(s.ScaleX).IsEqualTo(100);
        await Assert.That(s.ScaleY).IsEqualTo(100);
        await Assert.That(s.Spacing).IsEqualTo(0);
        await Assert.That(s.Angle).IsEqualTo(0);
        await Assert.That(s.BorderStyle).IsEqualTo(1);
        await Assert.That(s.BorderThickness).IsEqualTo(4.4d);
        await Assert.That(s.ShadowDistance).IsEqualTo(2.2d);
        await Assert.That(s.Alignment).IsEqualTo(2);
        await Assert.That(s.Margins).IsEqualTo(new Margins(275, 275, 60));
        await Assert.That(s.Encoding).IsEqualTo(1);
    }

    [Test]
    public async Task FromAss_Ccs()
    {
        var s = Style.FromAss(1, CcsStyle);

        await Assert.That(s).IsNotNull();
        await Assert.That(s.Name).IsEqualTo("Default");
        await Assert.That(s.FontFamily).IsEqualTo("Arial");
        await Assert.That(s.FontSize).IsEqualTo(24);
        await Assert.That(s.ScaleX).IsEqualTo(100);
        await Assert.That(s.ScaleY).IsEqualTo(100);
        await Assert.That(s.Spacing).IsEqualTo(0);
        await Assert.That(s.Angle).IsEqualTo(0);
        await Assert.That(s.BorderStyle).IsEqualTo(1);
        await Assert.That(s.BorderThickness).IsEqualTo(1d);
        await Assert.That(s.ShadowDistance).IsEqualTo(2d);
        await Assert.That(s.Margins).IsEqualTo(new Margins(25, 25, 25));
        await Assert.That(s.Encoding).IsEqualTo(0);
    }

    [Test]
    public async Task FromAss_Malformed_ReturnsNull()
    {
        var style = Style.FromAss(1, "Mark's Pizzeria! Did you know kaakaadhiweijqojfofw");

        await Assert.That(style).IsNull();
    }

    [Test]
    public async Task AsAss()
    {
        var s = Style.FromAss(1, BasicStyle);

        await Assert.That(s).IsNotNull();
        await Assert.That(s.AsAss()).IsEqualTo(BasicStyle);
    }

    [Test]
    public async Task Clone()
    {
        var s1 = Style.FromAss(1, BasicStyle)!;
        var s2 = s1.Clone();

        await Assert.That(s2).IsEqualTo(s1);
    }

    [Test]
    public async Task Equals_True()
    {
        var style1 = new Style(1) { Name = "TestStyle" };
        var style2 = new Style(1) { Name = "TestStyle" };

        await Assert.That(style1).IsEqualTo(style2);
    }

    [Test]
    public async Task Equals_False()
    {
        var style1 = new Style(1) { Name = "StyleA" };
        var style2 = new Style(2) { Name = "StyleB" };

        await Assert.That(style1).IsNotEqualTo(style2);
    }
}
